///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ContextCreation
{
    public partial class ActionsInCriteria
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void NamedSelectedCriteria(RepoItemInfo labeltagInfo , RepoItemInfo inputtagInfo )
        {
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'labeltagInfo' at 7;9.", labeltagInfo);
            //labeltagInfo = labeltagInfo.FindAdapter<LabelTag>();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>'eye makeover / custom.content_type ') on item 'labeltagInfo'.", labeltagInfo);
            Validate.AttributeContains(labeltagInfo, "Text", "eye makeover / custom.content_type ");
            
           // if(labeltagInfo.)
          //  {
            //	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo' at Center.", inputtagInfo);
            //	inputtagInfo.FindAdapter<InputTag>().Click();
          
            //}
            
        }

        public void Validate_SelectAttachNamedCriteri(RepoItemInfo labeltagInfo)
        {
            // TODO: Replace the following line with your code implementation.
            throw new NotImplementedException();
        }

       

    }
}
