///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ContextCreation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddFilters recording.
    /// </summary>
    [TestModule("c85b97e3-6f90-46e0-b2bf-dba1b14e3c77", ModuleType.Recording, 1)]
    public partial class AddFilters : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ContextCreationRepository repository.
        /// </summary>
        public static ContextCreationRepository repo = ContextCreationRepository.Instance;

        static AddFilters instance = new AddFilters();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddFilters()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddFilters Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EditContext' at 17;6.", repo.ApplicationUnderTest.EditContextInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.EditContext.Click("17;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddFilters' at 5;15.", repo.ApplicationUnderTest.AddFiltersInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.AddFilters.Click("5;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BrandSafetyFilter_SafeFromAccidents' at 66;23.", repo.ApplicationUnderTest.BrandSafetyFilter_SafeFromAccidentsInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BrandSafetyFilter_SafeFromAccidents.Click("66;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BrandSafetyFilter_SafeFromIllegalDownload' at 81;23.", repo.ApplicationUnderTest.BrandSafetyFilter_SafeFromIllegalDownloadInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.BrandSafetyFilter_SafeFromIllegalDownload.Click("81;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -83 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(-83);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TopicFilter_StyleAndFashion' at 75;12.", repo.ApplicationUnderTest.TopicFilter_StyleAndFashionInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.TopicFilter_StyleAndFashion.Click("75;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 619 units.", new RecordItemIndex(6));
            Mouse.ScrollWheel(619);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SavePublish' at 74;7.", repo.ApplicationUnderTest.SavePublishInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.SavePublish.Click("74;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EditContext' at 18;7.", repo.ApplicationUnderTest.EditContextInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.EditContext.Click("18;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddCalibrateOutput' at 0;13.", repo.ApplicationUnderTest.AddCalibrateOutputInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.AddCalibrateOutput.Click("0;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SelectTopNPercentage' at 9;9.", repo.ApplicationUnderTest.SelectTopNPercentageInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.SelectTopNPercentage.Click("9;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TopNPercentageValue' at 20;10.", repo.ApplicationUnderTest.TopNPercentageValueInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.TopNPercentageValue.Click("20;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '101' with focus on 'ApplicationUnderTest.TopNPercentageValue'.", repo.ApplicationUnderTest.TopNPercentageValueInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.TopNPercentageValue.PressKeys("101");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EnableHourlyRefresh' at 5;13.", repo.ApplicationUnderTest.EnableHourlyRefreshInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.EnableHourlyRefresh.Click("5;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TopNPercentageValue' at 53;13.", repo.ApplicationUnderTest.TopNPercentageValueInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.TopNPercentageValue.Click("53;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}' with focus on 'ApplicationUnderTest.TopNPercentageValue'.", repo.ApplicationUnderTest.TopNPercentageValueInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.TopNPercentageValue.PressKeys("{Back}{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'ApplicationUnderTest.TopNPercentageValue'.", repo.ApplicationUnderTest.TopNPercentageValueInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.TopNPercentageValue.PressKeys("50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EnableHourlyRefresh' at 6;4.", repo.ApplicationUnderTest.EnableHourlyRefreshInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.EnableHourlyRefresh.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EnableHourlyRefresh' at 6;7.", repo.ApplicationUnderTest.EnableHourlyRefreshInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.EnableHourlyRefresh.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.SavePublish' at 99;21.", repo.ApplicationUnderTest.SavePublishInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.SavePublish.MoveTo("99;21");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.SavePublish' at 99;21.", repo.ApplicationUnderTest.SavePublishInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.SavePublish.MoveTo("99;21");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Show' at 18;13.", repo.ApplicationUnderTest.ShowInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.Show.Click("18;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PreviewResultsContext' at 74;25.", repo.ApplicationUnderTest.PreviewResultsContextInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.PreviewResultsContext.Click("74;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -491 units.", new RecordItemIndex(23));
            Mouse.ScrollWheel(-491);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1361 units.", new RecordItemIndex(24));
            Mouse.ScrollWheel(1361);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CloseContext' at 22;5.", repo.ApplicationUnderTest.CloseContextInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.CloseContext.Click("22;5");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
