///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ContextCreation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddPagelistWithActions recording.
    /// </summary>
    [TestModule("48d211ad-b23d-45b3-b742-9aa8060270c5", ModuleType.Recording, 1)]
    public partial class AddPagelistWithActions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ContextCreationRepository repository.
        /// </summary>
        public static ContextCreationRepository repo = ContextCreationRepository.Instance;

        static AddPagelistWithActions instance = new AddPagelistWithActions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddPagelistWithActions()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddPagelistWithActions Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EditContext' at 8;4.", repo.ApplicationUnderTest.EditContextInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.EditContext.Click("8;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddPagelist' at 306;8.", repo.ApplicationUnderTest.AddPagelistInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.AddPagelist.Click("306;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AttachPageList' at 80;10.", repo.ApplicationUnderTest.AttachPageListInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.AttachPageList.Click("80;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PageListCheckbox' at 3;13.", repo.ApplicationUnderTest.PageListCheckboxInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.PageListCheckbox.Click("3;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IncludePagelist' at 57;8.", repo.ApplicationUnderTest.IncludePagelistInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.IncludePagelist.Click("57;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -965 units.", new RecordItemIndex(5));
            Mouse.ScrollWheel(-965);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AttachSelectedPageList' at 50;12.", repo.ApplicationUnderTest.AttachSelectedPageListInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.AttachSelectedPageList.Click("50;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ExcludePagelist' at 38;16.", repo.ApplicationUnderTest.ExcludePagelistInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.ExcludePagelist.Click("38;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SavePublish' at 83;22.", repo.ApplicationUnderTest.SavePublishInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.SavePublish.Click("83;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EditContext' at 8;8.", repo.ApplicationUnderTest.EditContextInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.EditContext.Click("8;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddPagelist' at 71;15.", repo.ApplicationUnderTest.AddPagelistInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.AddPagelist.Click("71;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AttachPageList' at 90;8.", repo.ApplicationUnderTest.AttachPageListInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.AttachPageList.Click("90;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100 units.", new RecordItemIndex(12));
            Mouse.ScrollWheel(-100);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PageList1Checkbox' at 6;9.", repo.ApplicationUnderTest.PageList1CheckboxInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.PageList1Checkbox.Click("6;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -5720 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-5720);
            Delay.Milliseconds(400);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest' at 1434;434.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(15));
            //repo.ApplicationUnderTest.Self.MoveTo("1434;434");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AttachSelectedPageList' at 12;11.", repo.ApplicationUnderTest.AttachSelectedPageListInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.AttachSelectedPageList.Click("12;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IncludePagelist' at 30;15.", repo.ApplicationUnderTest.IncludePagelistInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.IncludePagelist.Click("30;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IncludePagelist' at 30;15.", repo.ApplicationUnderTest.IncludePagelistInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.IncludePagelist.Click("30;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SavePublish' at 77;21.", repo.ApplicationUnderTest.SavePublishInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.SavePublish.Click("77;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Show' at 14;3.", repo.ApplicationUnderTest.ShowInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.Show.Click("14;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PreviewResultsContext' at 14;3.", repo.ApplicationUnderTest.PreviewResultsContextInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.PreviewResultsContext.Click("14;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CloseContext' at 15;4.", repo.ApplicationUnderTest.CloseContextInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.CloseContext.Click("15;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EditContext' at 9;9.", repo.ApplicationUnderTest.EditContextInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.EditContext.Click("9;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddPagelist' at 62;14.", repo.ApplicationUnderTest.AddPagelistInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.AddPagelist.Click("62;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AttachPageList' at 28;10.", repo.ApplicationUnderTest.AttachPageListInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.AttachPageList.Click("28;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -965 units.", new RecordItemIndex(26));
            Mouse.ScrollWheel(-965);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -965 units.", new RecordItemIndex(27));
            Mouse.ScrollWheel(-965);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ClosePagelistInContext' at 28;10.", repo.ApplicationUnderTest.ClosePagelistInContextInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.ClosePagelistInContext.Click("28;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SavePublish' at 78;17.", repo.ApplicationUnderTest.SavePublishInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.SavePublish.Click("78;17");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
