///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NamedCriteria
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNamedCriteria recording.
    /// </summary>
    [TestModule("1ef8af2a-f695-44a0-acb7-600efe1d19f1", ModuleType.Recording, 1)]
    public partial class CreateNamedCriteria : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NamedCriteriaRepository repository.
        /// </summary>
        public static NamedCriteriaRepository repo = NamedCriteriaRepository.Instance;

        static CreateNamedCriteria instance = new CreateNamedCriteria();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNamedCriteria()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNamedCriteria Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserEmail' at 27;9.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.UserEmail.Click("27;9", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'priyanka{RShiftKey down}_{RShiftKey up}ramesh{RShiftKey down}@{RShiftKey up}condenast.com' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.UserEmail.PressKeys("priyanka{RShiftKey down}_{RShiftKey up}ramesh{RShiftKey down}@{RShiftKey up}condenast.com", 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserPassword' at 66;15.", repo.ApplicationUnderTest.UserPasswordInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.UserPassword.Click("66;15", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'obsidian' with focus on 'ApplicationUnderTest.UserPassword'.", repo.ApplicationUnderTest.UserPasswordInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.UserPassword.PressKeys("obsidian", 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginButton' at 82;10.", repo.ApplicationUnderTest.LoginButtonInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.LoginButton.Click("82;10", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ContextStudio_ToUserPortal' at 66;5.", repo.ApplicationUnderTest.ContextStudio_ToUserPortalInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.ContextStudio_ToUserPortal.Click("66;5", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NAMEDCRITERIA' at 116;3.", repo.ApplicationUnderTest.NAMEDCRITERIAInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.NAMEDCRITERIA.Click("116;3", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNamedCriteria' at 1147;175.", repo.ApplicationUnderTest.CreateNamedCriteriaInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.CreateNamedCriteria.Click("1147;175", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NamedCriteriaName' at 531;23.", repo.ApplicationUnderTest.NamedCriteriaNameInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.NamedCriteriaName.Click("531;23", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hair style' with focus on 'ApplicationUnderTest.NamedCriteriaName'.", repo.ApplicationUnderTest.NamedCriteriaNameInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.NamedCriteriaName.PressKeys("Hair style", 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RawCriteria' at 233;40.", repo.ApplicationUnderTest.RawCriteriaInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.RawCriteria.Click("233;40", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}\"{RShiftKey up}curls{RShiftKey down}\"{RShiftKey up} {RShiftKey down}\"{RShiftKey up}ponytail{RShiftKey down}\"{RShiftKey up} {RShiftKey down}{\" down}{RShiftKey up}' with focus on 'ApplicationUnderTest.RawCriteria'.", repo.ApplicationUnderTest.RawCriteriaInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.RawCriteria.PressKeys("{RShiftKey down}\"{RShiftKey up}curls{RShiftKey down}\"{RShiftKey up} {RShiftKey down}\"{RShiftKey up}ponytail{RShiftKey down}\"{RShiftKey up} {RShiftKey down}{\" down}{RShiftKey up}", 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'straighten{RShiftKey down}\"{RShiftKey up}' with focus on 'ApplicationUnderTest.RawCriteria'.", repo.ApplicationUnderTest.RawCriteriaInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.RawCriteria.PressKeys("straighten{RShiftKey down}\"{RShiftKey up}", 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PreviewResults' at 28;16.", repo.ApplicationUnderTest.PreviewResultsInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.PreviewResults.Click("28;16", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -272 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-272);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 2112 units.", new RecordItemIndex(15));
            Mouse.ScrollWheel(2112);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SaveNamedCriteria' at 71;13.", repo.ApplicationUnderTest.SaveNamedCriteriaInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.SaveNamedCriteria.Click("71;13", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NamedCriteriaSearch' at 590;23.", repo.ApplicationUnderTest.NamedCriteriaSearchInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.NamedCriteriaSearch.Click("590;23", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hair' with focus on 'ApplicationUnderTest.NamedCriteriaSearch'.", repo.ApplicationUnderTest.NamedCriteriaSearchInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.NamedCriteriaSearch.PressKeys("hair", 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ClearSearch' at 56;6.", repo.ApplicationUnderTest.ClearSearchInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.ClearSearch.Click("56;6", 300);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
