///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NamedCriteria
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NamedCriteriaActions recording.
    /// </summary>
    [TestModule("7e18166e-6c2b-485e-bd1b-a062f7d736a1", ModuleType.Recording, 1)]
    public partial class NamedCriteriaActions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NamedCriteriaRepository repository.
        /// </summary>
        public static NamedCriteriaRepository repo = NamedCriteriaRepository.Instance;

        static NamedCriteriaActions instance = new NamedCriteriaActions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NamedCriteriaActions()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NamedCriteriaActions Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.Show' at 17;6.", repo.ApplicationUnderTest.PaddingTop100Row.ShowInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.PaddingTop100Row.Show.Click("17;6", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.Show' at 17;6.", repo.ApplicationUnderTest.PaddingTop100Row.ShowInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.PaddingTop100Row.Show.Click("17;6", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PreviewResults' at 63;19.", repo.ApplicationUnderTest.PreviewResultsInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.PreviewResults.Click("63;19", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -311 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-311);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 461 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(461);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CloseNamedCriteria' at 19;3.", repo.ApplicationUnderTest.CloseNamedCriteriaInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.CloseNamedCriteria.Click("19;3", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria'", repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteriaInfo, new ActionTimeout(5000), new RecordItemIndex(6));
            repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteriaInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria' at 18;3.", repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteriaInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria.Click("18;3", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NamedCriteriaDescription' at 445;11.", repo.ApplicationUnderTest.NamedCriteriaDescriptionInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.NamedCriteriaDescription.Click("445;11", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'ApplicationUnderTest.NamedCriteriaDescription'.", repo.ApplicationUnderTest.NamedCriteriaDescriptionInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.NamedCriteriaDescription.PressKeys("test", 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FormLogin.Copy_of_TargetLanguage' at 36;18.", repo.ApplicationUnderTest.FormLogin.Copy_of_TargetLanguageInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.FormLogin.Copy_of_TargetLanguage.Click("36;18", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SelectTargetLanguage' at 48;12.", repo.ApplicationUnderTest.SelectTargetLanguageInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.SelectTargetLanguage.Click("48;12", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.FormLogin.Criteria_type_update'", repo.ApplicationUnderTest.FormLogin.Criteria_type_updateInfo, new ActionTimeout(5000), new RecordItemIndex(12));
            repo.ApplicationUnderTest.FormLogin.Criteria_type_updateInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FormLogin.Criteria_type_update' at 56;19.", repo.ApplicationUnderTest.FormLogin.Criteria_type_updateInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.FormLogin.Criteria_type_update.Click("56;19", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FormLogin.SelectEntireContent' at 50;16.", repo.ApplicationUnderTest.FormLogin.SelectEntireContentInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.FormLogin.SelectEntireContent.Click("50;16", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PreviewResults' at 52;20.", repo.ApplicationUnderTest.PreviewResultsInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.PreviewResults.Click("52;20", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SaveNamedCriteria' at 111;25.", repo.ApplicationUnderTest.SaveNamedCriteriaInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.SaveNamedCriteria.Click("111;25", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria' at 14;2.", repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteriaInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria.Click("14;2", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FormLogin.Criteria_type_update' at 62;24.", repo.ApplicationUnderTest.FormLogin.Criteria_type_updateInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.FormLogin.Criteria_type_update.Click("62;24", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FormLogin.SelectQueryByField' at 56;28.", repo.ApplicationUnderTest.FormLogin.SelectQueryByFieldInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.FormLogin.SelectQueryByField.Click("56;28", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.SelectHALKeywordsField' at 54;14.", repo.ApplicationUnderTest.PaddingTop100Row.SelectHALKeywordsFieldInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.PaddingTop100Row.SelectHALKeywordsField.Click("54;14", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.GetResult' at 11;13.", repo.ApplicationUnderTest.PaddingTop100Row.GetResultInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.PaddingTop100Row.GetResult.Click("11;13", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UpdateCriteria' at 52;24.", repo.ApplicationUnderTest.UpdateCriteriaInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.UpdateCriteria.Click("52;24", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.Show' at 5;6.", repo.ApplicationUnderTest.PaddingTop100Row.ShowInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.PaddingTop100Row.Show.Click("5;6", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PreviewResults' at 58;18.", repo.ApplicationUnderTest.PreviewResultsInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.PreviewResults.Click("58;18", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CloseNamedCriteria' at 20;6.", repo.ApplicationUnderTest.CloseNamedCriteriaInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.CloseNamedCriteria.Click("20;6", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria_QueryFromField'", repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria_QueryFromFieldInfo, new ActionTimeout(5000), new RecordItemIndex(26));
            repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria_QueryFromFieldInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria_QueryFromField' at 16;11.", repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria_QueryFromFieldInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria_QueryFromField.Click("16;11", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.CriteriaType_QueryByfield' at 129;22.", repo.ApplicationUnderTest.PaddingTop100Row.CriteriaType_QueryByfieldInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.PaddingTop100Row.CriteriaType_QueryByfield.Click("129;22", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.SelectEntireCriteriaContentType' at 112;9.", repo.ApplicationUnderTest.PaddingTop100Row.SelectEntireCriteriaContentTypeInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.PaddingTop100Row.SelectEntireCriteriaContentType.Click("112;9", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.GetResult' at 31;21.", repo.ApplicationUnderTest.PaddingTop100Row.GetResultInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.PaddingTop100Row.GetResult.Click("31;21", 300);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UpdateCriteria' at 72;17.", repo.ApplicationUnderTest.UpdateCriteriaInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.UpdateCriteria.Click("72;17", 300);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
