///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace NamedCriteria
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NamedCriteriaRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("bf7e67d4-f05c-4862-ab3c-bb158e1d5105")]
    public partial class NamedCriteriaRepository : RepoGenBaseFolder
    {
        static NamedCriteriaRepository instance = new NamedCriteriaRepository();
        NamedCriteriaRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the NamedCriteriaRepository element repository.
        /// </summary>
        [RepositoryFolder("bf7e67d4-f05c-4862-ab3c-bb158e1d5105")]
        public static NamedCriteriaRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NamedCriteriaRepository() 
            : base("NamedCriteriaRepository", "/", null, 0, false, "bf7e67d4-f05c-4862-ab3c-bb158e1d5105", ".\\RepositoryImages\\NamedCriteriaRepositorybf7e67d4.rximgres")
        {
            _applicationundertest = new NamedCriteriaRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

        string _NewVariable = "NAMED CRITERIA";

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("3b29223b-92c0-4808-ab5e-d81198eb02c9")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

        string _NewVariable1 = "http://obsidian-staging.conde.io/named_criteria/show/848";

        /// <summary>
        /// Gets or sets the value of variable NewVariable1.
        /// </summary>
        [TestVariable("69c19ca9-8f2e-4814-8b76-0e1f8f8061cb")]
        public string NewVariable1
        {
            get { return _NewVariable1; }
            set { _NewVariable1 = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bf7e67d4-f05c-4862-ab3c-bb158e1d5105")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("34089432-bae7-4308-8448-81979698d8cb")]
        public virtual NamedCriteriaRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class NamedCriteriaRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("34089432-bae7-4308-8448-81979698d8cb")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            NamedCriteriaRepositoryFolders.PaddingTop100RowFolder _paddingtop100row;
            NamedCriteriaRepositoryFolders.FormLoginFolder _formlogin;
            RepoItemInfo _useremailInfo;
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _contextstudio_touserportalInfo;
            RepoItemInfo _namedcriteriaInfo;
            RepoItemInfo _createnamedcriteriaInfo;
            RepoItemInfo _namedcriterianameInfo;
            RepoItemInfo _previewresultsInfo;
            RepoItemInfo _savenamedcriteriaInfo;
            RepoItemInfo _namedcriteriasearchInfo;
            RepoItemInfo _clearsearchInfo;
            RepoItemInfo _closenamedcriteriaInfo;
            RepoItemInfo _namedcriteriadescriptionInfo;
            RepoItemInfo _selecttargetlanguageInfo;
            RepoItemInfo _updatecriteriaInfo;
            RepoItemInfo _englishInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _adminuserInfo;
            RepoItemInfo _ataglogoutInfo;
            RepoItemInfo _querytooltabInfo;
            RepoItemInfo _rawcriteriaquerytoolInfo;
            RepoItemInfo _criteriatypequerytoolInfo;
            RepoItemInfo _targetlanguagequerytoolInfo;
            RepoItemInfo _shownamedcriteriaInfo;
            RepoItemInfo _datasourcequerytoolInfo;
            RepoItemInfo _querynowquerytoolInfo;
            RepoItemInfo _savenamedinquerytoolInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='obsidian-staging.conde.io']", parentFolder, 30000, null, false, "34089432-bae7-4308-8448-81979698d8cb", "")
            {
                _paddingtop100row = new NamedCriteriaRepositoryFolders.PaddingTop100RowFolder(this);
                _formlogin = new NamedCriteriaRepositoryFolders.FormLoginFolder(this);
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "8b18f50d-93e6-445b-8f44-e87a26d36b50");
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "58a1d682-2fd0-4fcd-a8c9-e2a7fbdaa82c");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "60564e4c-42b3-45bc-a799-ebbe18d23be8");
                _contextstudio_touserportalInfo = new RepoItemInfo(this, "ContextStudio_ToUserPortal", ".//h1[#'site_title']/a[@innertext='Context Studio']", 30000, null, "4863fb3e-a395-4cf1-9ec9-13f371f42533");
                _namedcriteriaInfo = new RepoItemInfo(this, "NAMEDCRITERIA", ".//a[@innertext='NAMED CRITERIA']", 30000, null, "8a0de1ab-83f5-47c0-9721-f669557df518");
                _createnamedcriteriaInfo = new RepoItemInfo(this, "CreateNamedCriteria", ".//input[@class='action-button float-right']", 30000, null, "6bb24f5e-a7e3-440f-bf02-80d683e17b8c");
                _namedcriterianameInfo = new RepoItemInfo(this, "NamedCriteriaName", ".//input[#'named-criteria-name']", 30000, null, "82ffb288-2c01-491d-a352-efc9d0422998");
                _previewresultsInfo = new RepoItemInfo(this, "PreviewResults", "body/div[1]/div/div/div/div[2]/input[@value='Preview Results']", 30000, null, "9dee361f-821e-4e08-9f8c-b8c2ab121d0c");
                _savenamedcriteriaInfo = new RepoItemInfo(this, "SaveNamedCriteria", "body/div[1]/div/div/div/div[2]/input[@value='Save Named Criteria']", 30000, null, "0793412a-a551-41de-a8e6-8867ebde5342");
                _namedcriteriasearchInfo = new RepoItemInfo(this, "NamedCriteriaSearch", "body/div/div[2]/div[1]/div/div[1]/input[@type='text']", 30000, null, "9b06d676-2086-4c62-a179-66bcc0125df3");
                _clearsearchInfo = new RepoItemInfo(this, "ClearSearch", "body/div/div[2]/div[1]/?/?/span/a[@class='clear-named-criteria']", 30000, null, "ed06735c-5125-4f4f-bfe1-7fab0bd7cadc");
                _closenamedcriteriaInfo = new RepoItemInfo(this, "CloseNamedCriteria", "body/div[1]/div/div/div/div[2]/?/?/a[@innertext='Close']", 30000, null, "64f7f432-cf17-4092-8eab-a972d088e0a5");
                _namedcriteriadescriptionInfo = new RepoItemInfo(this, "NamedCriteriaDescription", ".//input[#'named-criteria-description']", 30000, null, "d400a253-ae05-4d72-a338-f4446638a3a4");
                _selecttargetlanguageInfo = new RepoItemInfo(this, "SelectTargetLanguage", "body/div[2]/div[1]/div[1]/div[3]/div[2]/ul/li[2]/a[@innertext='English']", 30000, null, "659d6b4e-ab4d-4052-b9e3-9880ce6ea30d");
                _updatecriteriaInfo = new RepoItemInfo(this, "UpdateCriteria", ".//input[#'create_criteria']", 30000, null, "36192e84-7065-4310-9912-9c536195e400");
                _englishInfo = new RepoItemInfo(this, "English", ".//ul[#'target-language']/?/?/a[@innertext='English']", 30000, null, "cbdcfa52-691c-4a2c-bba0-cb73d20b4614");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//table/tbody/tr[1]/td[5]/span[@innertext>' /                      /']/a[@innertext='Delete']", 30000, null, "b2ac4856-754a-49f7-bae2-966d5111cf4a");
                _adminuserInfo = new RepoItemInfo(this, "AdminUser", "body/div//button[@innertext='Admin User ']", 30000, null, "3f410c1b-f7c6-4a19-9031-85cf13990451");
                _ataglogoutInfo = new RepoItemInfo(this, "ATagLogout", ".//div[#'myDropdown']/a[@innertext='  Logout']", 30000, null, "f2dbb819-d5bf-483b-a4ef-71c5181ee1c1");
                _querytooltabInfo = new RepoItemInfo(this, "QueryToolTab", ".//a[@innertext='QUERY TOOL' and @visible='True']", 30000, null, "ca5cbf0b-8cdb-4e11-9f04-bf1d6ef93e6b");
                _rawcriteriaquerytoolInfo = new RepoItemInfo(this, "RawCriteriaQueryTool", ".//textarea[@id='raw-criteria']", 30000, null, "abe17b28-dee4-4a07-a4e9-5a3924ab4c62");
                _criteriatypequerytoolInfo = new RepoItemInfo(this, "CriteriaTypeQueryTool", ".//buttontag[@class='button-link dropdown-toggle drop-down-title btn float-right criteria-type display-flex' and @visible='True']", 30000, null, "07b21608-ffce-410f-b0cc-81164480efd4");
                _targetlanguagequerytoolInfo = new RepoItemInfo(this, "TargetLanguageQueryTool", ".//buttontag[@class='button-link dropdown-toggle drop-down-title btn float-right target-language  display-flex' and @visible='True']", 30000, null, "1b4d3720-88c2-4aa7-8795-6036f534defb");
                _shownamedcriteriaInfo = new RepoItemInfo(this, "ShowNamedCriteria", ".//a[@innertext='Show' and @visible='True'][1]", 30000, null, "f4a8ad15-924a-4417-87a2-dcc88c1b94c3");
                _datasourcequerytoolInfo = new RepoItemInfo(this, "DatasourceQueryTool", ".//buttontag[@class='button-link dropdown-toggle drop-down-title btn btn float-right display-flex data-source' and @visible='True'][1]", 30000, null, "f203e6d8-55bf-4931-afbf-e01a926c4a2e");
                _querynowquerytoolInfo = new RepoItemInfo(this, "QueryNowQueryTool", ".//input[@class='action-button float-right preview_results' and @visible='True']", 30000, null, "48af2c94-b7e6-4574-bca7-e8a874c01003");
                _savenamedinquerytoolInfo = new RepoItemInfo(this, "SaveNamedInQueryTool", ".//input[@class='action-button save-named-criteria' and @visible='True']", 30000, null, "16a0bb94-f270-448e-a7fc-bea10565765f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("34089432-bae7-4308-8448-81979698d8cb")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("34089432-bae7-4308-8448-81979698d8cb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("8b18f50d-93e6-445b-8f44-e87a26d36b50")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("8b18f50d-93e6-445b-8f44-e87a26d36b50")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("58a1d682-2fd0-4fcd-a8c9-e2a7fbdaa82c")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("58a1d682-2fd0-4fcd-a8c9-e2a7fbdaa82c")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("60564e4c-42b3-45bc-a799-ebbe18d23be8")]
            public virtual Ranorex.InputTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("60564e4c-42b3-45bc-a799-ebbe18d23be8")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The ContextStudio_ToUserPortal item.
            /// </summary>
            [RepositoryItem("4863fb3e-a395-4cf1-9ec9-13f371f42533")]
            public virtual Ranorex.ATag ContextStudio_ToUserPortal
            {
                get
                {
                    return _contextstudio_touserportalInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ContextStudio_ToUserPortal item info.
            /// </summary>
            [RepositoryItemInfo("4863fb3e-a395-4cf1-9ec9-13f371f42533")]
            public virtual RepoItemInfo ContextStudio_ToUserPortalInfo
            {
                get
                {
                    return _contextstudio_touserportalInfo;
                }
            }

            /// <summary>
            /// The NAMEDCRITERIA item.
            /// </summary>
            [RepositoryItem("8a0de1ab-83f5-47c0-9721-f669557df518")]
            public virtual Ranorex.ATag NAMEDCRITERIA
            {
                get
                {
                    return _namedcriteriaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NAMEDCRITERIA item info.
            /// </summary>
            [RepositoryItemInfo("8a0de1ab-83f5-47c0-9721-f669557df518")]
            public virtual RepoItemInfo NAMEDCRITERIAInfo
            {
                get
                {
                    return _namedcriteriaInfo;
                }
            }

            /// <summary>
            /// The CreateNamedCriteria item.
            /// </summary>
            [RepositoryItem("6bb24f5e-a7e3-440f-bf02-80d683e17b8c")]
            public virtual Ranorex.InputTag CreateNamedCriteria
            {
                get
                {
                    return _createnamedcriteriaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CreateNamedCriteria item info.
            /// </summary>
            [RepositoryItemInfo("6bb24f5e-a7e3-440f-bf02-80d683e17b8c")]
            public virtual RepoItemInfo CreateNamedCriteriaInfo
            {
                get
                {
                    return _createnamedcriteriaInfo;
                }
            }

            /// <summary>
            /// The NamedCriteriaName item.
            /// </summary>
            [RepositoryItem("82ffb288-2c01-491d-a352-efc9d0422998")]
            public virtual Ranorex.InputTag NamedCriteriaName
            {
                get
                {
                    return _namedcriterianameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NamedCriteriaName item info.
            /// </summary>
            [RepositoryItemInfo("82ffb288-2c01-491d-a352-efc9d0422998")]
            public virtual RepoItemInfo NamedCriteriaNameInfo
            {
                get
                {
                    return _namedcriterianameInfo;
                }
            }

            /// <summary>
            /// The PreviewResults item.
            /// </summary>
            [RepositoryItem("9dee361f-821e-4e08-9f8c-b8c2ab121d0c")]
            public virtual Ranorex.InputTag PreviewResults
            {
                get
                {
                    return _previewresultsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PreviewResults item info.
            /// </summary>
            [RepositoryItemInfo("9dee361f-821e-4e08-9f8c-b8c2ab121d0c")]
            public virtual RepoItemInfo PreviewResultsInfo
            {
                get
                {
                    return _previewresultsInfo;
                }
            }

            /// <summary>
            /// The SaveNamedCriteria item.
            /// </summary>
            [RepositoryItem("0793412a-a551-41de-a8e6-8867ebde5342")]
            public virtual Ranorex.InputTag SaveNamedCriteria
            {
                get
                {
                    return _savenamedcriteriaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SaveNamedCriteria item info.
            /// </summary>
            [RepositoryItemInfo("0793412a-a551-41de-a8e6-8867ebde5342")]
            public virtual RepoItemInfo SaveNamedCriteriaInfo
            {
                get
                {
                    return _savenamedcriteriaInfo;
                }
            }

            /// <summary>
            /// The NamedCriteriaSearch item.
            /// </summary>
            [RepositoryItem("9b06d676-2086-4c62-a179-66bcc0125df3")]
            public virtual Ranorex.InputTag NamedCriteriaSearch
            {
                get
                {
                    return _namedcriteriasearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NamedCriteriaSearch item info.
            /// </summary>
            [RepositoryItemInfo("9b06d676-2086-4c62-a179-66bcc0125df3")]
            public virtual RepoItemInfo NamedCriteriaSearchInfo
            {
                get
                {
                    return _namedcriteriasearchInfo;
                }
            }

            /// <summary>
            /// The ClearSearch item.
            /// </summary>
            [RepositoryItem("ed06735c-5125-4f4f-bfe1-7fab0bd7cadc")]
            public virtual Ranorex.ATag ClearSearch
            {
                get
                {
                    return _clearsearchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ClearSearch item info.
            /// </summary>
            [RepositoryItemInfo("ed06735c-5125-4f4f-bfe1-7fab0bd7cadc")]
            public virtual RepoItemInfo ClearSearchInfo
            {
                get
                {
                    return _clearsearchInfo;
                }
            }

            /// <summary>
            /// The CloseNamedCriteria item.
            /// </summary>
            [RepositoryItem("64f7f432-cf17-4092-8eab-a972d088e0a5")]
            public virtual Ranorex.ATag CloseNamedCriteria
            {
                get
                {
                    return _closenamedcriteriaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CloseNamedCriteria item info.
            /// </summary>
            [RepositoryItemInfo("64f7f432-cf17-4092-8eab-a972d088e0a5")]
            public virtual RepoItemInfo CloseNamedCriteriaInfo
            {
                get
                {
                    return _closenamedcriteriaInfo;
                }
            }

            /// <summary>
            /// The NamedCriteriaDescription item.
            /// </summary>
            [RepositoryItem("d400a253-ae05-4d72-a338-f4446638a3a4")]
            public virtual Ranorex.InputTag NamedCriteriaDescription
            {
                get
                {
                    return _namedcriteriadescriptionInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NamedCriteriaDescription item info.
            /// </summary>
            [RepositoryItemInfo("d400a253-ae05-4d72-a338-f4446638a3a4")]
            public virtual RepoItemInfo NamedCriteriaDescriptionInfo
            {
                get
                {
                    return _namedcriteriadescriptionInfo;
                }
            }

            /// <summary>
            /// The SelectTargetLanguage item.
            /// </summary>
            [RepositoryItem("659d6b4e-ab4d-4052-b9e3-9880ce6ea30d")]
            public virtual Ranorex.ATag SelectTargetLanguage
            {
                get
                {
                    return _selecttargetlanguageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SelectTargetLanguage item info.
            /// </summary>
            [RepositoryItemInfo("659d6b4e-ab4d-4052-b9e3-9880ce6ea30d")]
            public virtual RepoItemInfo SelectTargetLanguageInfo
            {
                get
                {
                    return _selecttargetlanguageInfo;
                }
            }

            /// <summary>
            /// The UpdateCriteria item.
            /// </summary>
            [RepositoryItem("36192e84-7065-4310-9912-9c536195e400")]
            public virtual Ranorex.InputTag UpdateCriteria
            {
                get
                {
                    return _updatecriteriaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UpdateCriteria item info.
            /// </summary>
            [RepositoryItemInfo("36192e84-7065-4310-9912-9c536195e400")]
            public virtual RepoItemInfo UpdateCriteriaInfo
            {
                get
                {
                    return _updatecriteriaInfo;
                }
            }

            /// <summary>
            /// The English item.
            /// </summary>
            [RepositoryItem("cbdcfa52-691c-4a2c-bba0-cb73d20b4614")]
            public virtual Ranorex.ATag English
            {
                get
                {
                    return _englishInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The English item info.
            /// </summary>
            [RepositoryItemInfo("cbdcfa52-691c-4a2c-bba0-cb73d20b4614")]
            public virtual RepoItemInfo EnglishInfo
            {
                get
                {
                    return _englishInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("b2ac4856-754a-49f7-bae2-966d5111cf4a")]
            public virtual Ranorex.ATag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("b2ac4856-754a-49f7-bae2-966d5111cf4a")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The AdminUser item.
            /// </summary>
            [RepositoryItem("3f410c1b-f7c6-4a19-9031-85cf13990451")]
            public virtual Ranorex.ButtonTag AdminUser
            {
                get
                {
                    return _adminuserInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AdminUser item info.
            /// </summary>
            [RepositoryItemInfo("3f410c1b-f7c6-4a19-9031-85cf13990451")]
            public virtual RepoItemInfo AdminUserInfo
            {
                get
                {
                    return _adminuserInfo;
                }
            }

            /// <summary>
            /// The ATagLogout item.
            /// </summary>
            [RepositoryItem("f2dbb819-d5bf-483b-a4ef-71c5181ee1c1")]
            public virtual Ranorex.ATag ATagLogout
            {
                get
                {
                    return _ataglogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagLogout item info.
            /// </summary>
            [RepositoryItemInfo("f2dbb819-d5bf-483b-a4ef-71c5181ee1c1")]
            public virtual RepoItemInfo ATagLogoutInfo
            {
                get
                {
                    return _ataglogoutInfo;
                }
            }

            /// <summary>
            /// The QueryToolTab item.
            /// </summary>
            [RepositoryItem("ca5cbf0b-8cdb-4e11-9f04-bf1d6ef93e6b")]
            public virtual Ranorex.ATag QueryToolTab
            {
                get
                {
                    return _querytooltabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The QueryToolTab item info.
            /// </summary>
            [RepositoryItemInfo("ca5cbf0b-8cdb-4e11-9f04-bf1d6ef93e6b")]
            public virtual RepoItemInfo QueryToolTabInfo
            {
                get
                {
                    return _querytooltabInfo;
                }
            }

            /// <summary>
            /// The RawCriteriaQueryTool item.
            /// </summary>
            [RepositoryItem("abe17b28-dee4-4a07-a4e9-5a3924ab4c62")]
            public virtual Ranorex.TextAreaTag RawCriteriaQueryTool
            {
                get
                {
                    return _rawcriteriaquerytoolInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The RawCriteriaQueryTool item info.
            /// </summary>
            [RepositoryItemInfo("abe17b28-dee4-4a07-a4e9-5a3924ab4c62")]
            public virtual RepoItemInfo RawCriteriaQueryToolInfo
            {
                get
                {
                    return _rawcriteriaquerytoolInfo;
                }
            }

            /// <summary>
            /// The CriteriaTypeQueryTool item.
            /// </summary>
            [RepositoryItem("07b21608-ffce-410f-b0cc-81164480efd4")]
            public virtual Ranorex.ButtonTag CriteriaTypeQueryTool
            {
                get
                {
                    return _criteriatypequerytoolInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The CriteriaTypeQueryTool item info.
            /// </summary>
            [RepositoryItemInfo("07b21608-ffce-410f-b0cc-81164480efd4")]
            public virtual RepoItemInfo CriteriaTypeQueryToolInfo
            {
                get
                {
                    return _criteriatypequerytoolInfo;
                }
            }

            /// <summary>
            /// The TargetLanguageQueryTool item.
            /// </summary>
            [RepositoryItem("1b4d3720-88c2-4aa7-8795-6036f534defb")]
            public virtual Ranorex.ButtonTag TargetLanguageQueryTool
            {
                get
                {
                    return _targetlanguagequerytoolInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The TargetLanguageQueryTool item info.
            /// </summary>
            [RepositoryItemInfo("1b4d3720-88c2-4aa7-8795-6036f534defb")]
            public virtual RepoItemInfo TargetLanguageQueryToolInfo
            {
                get
                {
                    return _targetlanguagequerytoolInfo;
                }
            }

            /// <summary>
            /// The ShowNamedCriteria item.
            /// </summary>
            [RepositoryItem("f4a8ad15-924a-4417-87a2-dcc88c1b94c3")]
            public virtual Ranorex.ATag ShowNamedCriteria
            {
                get
                {
                    return _shownamedcriteriaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ShowNamedCriteria item info.
            /// </summary>
            [RepositoryItemInfo("f4a8ad15-924a-4417-87a2-dcc88c1b94c3")]
            public virtual RepoItemInfo ShowNamedCriteriaInfo
            {
                get
                {
                    return _shownamedcriteriaInfo;
                }
            }

            /// <summary>
            /// The DatasourceQueryTool item.
            /// </summary>
            [RepositoryItem("f203e6d8-55bf-4931-afbf-e01a926c4a2e")]
            public virtual Ranorex.ButtonTag DatasourceQueryTool
            {
                get
                {
                    return _datasourcequerytoolInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The DatasourceQueryTool item info.
            /// </summary>
            [RepositoryItemInfo("f203e6d8-55bf-4931-afbf-e01a926c4a2e")]
            public virtual RepoItemInfo DatasourceQueryToolInfo
            {
                get
                {
                    return _datasourcequerytoolInfo;
                }
            }

            /// <summary>
            /// The QueryNowQueryTool item.
            /// </summary>
            [RepositoryItem("48af2c94-b7e6-4574-bca7-e8a874c01003")]
            public virtual Ranorex.InputTag QueryNowQueryTool
            {
                get
                {
                    return _querynowquerytoolInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The QueryNowQueryTool item info.
            /// </summary>
            [RepositoryItemInfo("48af2c94-b7e6-4574-bca7-e8a874c01003")]
            public virtual RepoItemInfo QueryNowQueryToolInfo
            {
                get
                {
                    return _querynowquerytoolInfo;
                }
            }

            /// <summary>
            /// The SaveNamedInQueryTool item.
            /// </summary>
            [RepositoryItem("16a0bb94-f270-448e-a7fc-bea10565765f")]
            public virtual Ranorex.InputTag SaveNamedInQueryTool
            {
                get
                {
                    return _savenamedinquerytoolInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SaveNamedInQueryTool item info.
            /// </summary>
            [RepositoryItemInfo("16a0bb94-f270-448e-a7fc-bea10565765f")]
            public virtual RepoItemInfo SaveNamedInQueryToolInfo
            {
                get
                {
                    return _savenamedinquerytoolInfo;
                }
            }

            /// <summary>
            /// The PaddingTop100Row folder.
            /// </summary>
            [RepositoryFolder("93a2fb0e-e7df-400b-abc4-98a0f2bc5230")]
            public virtual NamedCriteriaRepositoryFolders.PaddingTop100RowFolder PaddingTop100Row
            {
                get { return _paddingtop100row; }
            }

            /// <summary>
            /// The FormLogin folder.
            /// </summary>
            [RepositoryFolder("e052f3f2-476a-4593-9776-bbd6f2c9089e")]
            public virtual NamedCriteriaRepositoryFolders.FormLoginFolder FormLogin
            {
                get { return _formlogin; }
            }
        }

        /// <summary>
        /// The PaddingTop100RowFolder folder.
        /// </summary>
        [RepositoryFolder("93a2fb0e-e7df-400b-abc4-98a0f2bc5230")]
        public partial class PaddingTop100RowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selectentirecriteriacontenttypeInfo;
            RepoItemInfo _selecthalkeywordsfieldInfo;
            RepoItemInfo _getresultInfo;
            RepoItemInfo _editnamedcriteria_queryfromfieldInfo;
            RepoItemInfo _editnamedcriteriaInfo;
            RepoItemInfo _showInfo;
            RepoItemInfo _criteriatype_querybyfieldInfo;
            RepoItemInfo _targetlanguageInfo;
            RepoItemInfo _testdatasourceInfo;
            RepoItemInfo _obsidianInfo;
            RepoItemInfo _buttontagokInfo;

            /// <summary>
            /// Creates a new PaddingTop100Row  folder.
            /// </summary>
            public PaddingTop100RowFolder(RepoGenBaseFolder parentFolder) :
                    base("PaddingTop100Row", "body/div/div[2]", parentFolder, 30000, null, false, "93a2fb0e-e7df-400b-abc4-98a0f2bc5230", "")
            {
                _selectentirecriteriacontenttypeInfo = new RepoItemInfo(this, "SelectEntireCriteriaContentType", "div[1]/div/div[1]/div[3]/ul/li[2]/a[@innertext='Entire Content']", 30000, null, "df264744-adff-44ca-85e2-0fd7613c3aff");
                _selecthalkeywordsfieldInfo = new RepoItemInfo(this, "SelectHALKeywordsField", "div[1]/div/div[2]/div[5]/span[@title='']", 30000, null, "fe7bd4e5-372d-4f3e-9ee8-0185244d5dbb");
                _getresultInfo = new RepoItemInfo(this, "GetResult", "div[2]/div/div[5]/input[@value='Get Result']", 30000, null, "b63fa525-76b9-422f-8389-1cb49d285097");
                _editnamedcriteria_queryfromfieldInfo = new RepoItemInfo(this, "EditNamedCriteria_QueryFromField", "div[3]/?/?/table/tbody/tr[1]/td[5]/span[@innertext>' /                      /']/a[@innertext='                    Edit']", 30000, null, "8fe8086d-e36c-4f87-b981-aa7c7abef755");
                _editnamedcriteriaInfo = new RepoItemInfo(this, "EditNamedCriteria", "div[3]/?/?/table/tbody/tr[1]/td[5]/span[@innertext>' /                      /']/a[@innertext='Edit']", 30000, null, "7dea1273-e107-45bf-acf7-c83564f49f88");
                _showInfo = new RepoItemInfo(this, "Show", "div[3]/?/?/table/tbody/tr[1]/td[5]/span[@innertext>' /                      /']/a[@innertext='Show']", 30000, null, "21b35f0d-3c6b-4cbb-9143-6cf8dab82f10");
                _criteriatype_querybyfieldInfo = new RepoItemInfo(this, "CriteriaType_QueryByfield", "div[1]/div/div[1]/div[3]/button[@class='btn btn-default dropdown-toggle drop-down-title float-right display-flex criteria-type']", 30000, null, "a77c2512-949d-4743-bdb2-c0d633680c15");
                _targetlanguageInfo = new RepoItemInfo(this, "TargetLanguage", "div[1]/div[2]//button[@title='Target Language']", 30000, null, "3f6d0e2d-b5f5-40f1-be49-6d0697af3b36");
                _testdatasourceInfo = new RepoItemInfo(this, "Testdatasource", "div[1]//ul/li[2]/a[@innertext='testdatasource']", 30000, null, "7d912d6e-5904-41e0-8f40-e2031471e486");
                _obsidianInfo = new RepoItemInfo(this, "Obsidian", "div[1]//ul/li[1]/a[@innertext='Obsidian']", 30000, null, "dab9a596-2928-4ae9-8c89-44d66746a098");
                _buttontagokInfo = new RepoItemInfo(this, "ButtonTagOk", ".//button[@innertext='Ok']", 30000, null, "49d8bcad-39b4-4a3c-9b4c-789a59fd4c98");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("93a2fb0e-e7df-400b-abc4-98a0f2bc5230")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("93a2fb0e-e7df-400b-abc4-98a0f2bc5230")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectEntireCriteriaContentType item.
            /// </summary>
            [RepositoryItem("df264744-adff-44ca-85e2-0fd7613c3aff")]
            public virtual Ranorex.ATag SelectEntireCriteriaContentType
            {
                get
                {
                    return _selectentirecriteriacontenttypeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SelectEntireCriteriaContentType item info.
            /// </summary>
            [RepositoryItemInfo("df264744-adff-44ca-85e2-0fd7613c3aff")]
            public virtual RepoItemInfo SelectEntireCriteriaContentTypeInfo
            {
                get
                {
                    return _selectentirecriteriacontenttypeInfo;
                }
            }

            /// <summary>
            /// The SelectHALKeywordsField item.
            /// </summary>
            [RepositoryItem("fe7bd4e5-372d-4f3e-9ee8-0185244d5dbb")]
            public virtual Ranorex.SpanTag SelectHALKeywordsField
            {
                get
                {
                    return _selecthalkeywordsfieldInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SelectHALKeywordsField item info.
            /// </summary>
            [RepositoryItemInfo("fe7bd4e5-372d-4f3e-9ee8-0185244d5dbb")]
            public virtual RepoItemInfo SelectHALKeywordsFieldInfo
            {
                get
                {
                    return _selecthalkeywordsfieldInfo;
                }
            }

            /// <summary>
            /// The GetResult item.
            /// </summary>
            [RepositoryItem("b63fa525-76b9-422f-8389-1cb49d285097")]
            public virtual Ranorex.InputTag GetResult
            {
                get
                {
                    return _getresultInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GetResult item info.
            /// </summary>
            [RepositoryItemInfo("b63fa525-76b9-422f-8389-1cb49d285097")]
            public virtual RepoItemInfo GetResultInfo
            {
                get
                {
                    return _getresultInfo;
                }
            }

            /// <summary>
            /// The EditNamedCriteria_QueryFromField item.
            /// </summary>
            [RepositoryItem("8fe8086d-e36c-4f87-b981-aa7c7abef755")]
            public virtual Ranorex.ATag EditNamedCriteria_QueryFromField
            {
                get
                {
                    return _editnamedcriteria_queryfromfieldInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EditNamedCriteria_QueryFromField item info.
            /// </summary>
            [RepositoryItemInfo("8fe8086d-e36c-4f87-b981-aa7c7abef755")]
            public virtual RepoItemInfo EditNamedCriteria_QueryFromFieldInfo
            {
                get
                {
                    return _editnamedcriteria_queryfromfieldInfo;
                }
            }

            /// <summary>
            /// The EditNamedCriteria item.
            /// </summary>
            [RepositoryItem("7dea1273-e107-45bf-acf7-c83564f49f88")]
            public virtual Ranorex.ATag EditNamedCriteria
            {
                get
                {
                    return _editnamedcriteriaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EditNamedCriteria item info.
            /// </summary>
            [RepositoryItemInfo("7dea1273-e107-45bf-acf7-c83564f49f88")]
            public virtual RepoItemInfo EditNamedCriteriaInfo
            {
                get
                {
                    return _editnamedcriteriaInfo;
                }
            }

            /// <summary>
            /// The Show item.
            /// </summary>
            [RepositoryItem("21b35f0d-3c6b-4cbb-9143-6cf8dab82f10")]
            public virtual Ranorex.ATag Show
            {
                get
                {
                    return _showInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Show item info.
            /// </summary>
            [RepositoryItemInfo("21b35f0d-3c6b-4cbb-9143-6cf8dab82f10")]
            public virtual RepoItemInfo ShowInfo
            {
                get
                {
                    return _showInfo;
                }
            }

            /// <summary>
            /// The CriteriaType_QueryByfield item.
            /// </summary>
            [RepositoryItem("a77c2512-949d-4743-bdb2-c0d633680c15")]
            public virtual Ranorex.ButtonTag CriteriaType_QueryByfield
            {
                get
                {
                    return _criteriatype_querybyfieldInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The CriteriaType_QueryByfield item info.
            /// </summary>
            [RepositoryItemInfo("a77c2512-949d-4743-bdb2-c0d633680c15")]
            public virtual RepoItemInfo CriteriaType_QueryByfieldInfo
            {
                get
                {
                    return _criteriatype_querybyfieldInfo;
                }
            }

            /// <summary>
            /// The TargetLanguage item.
            /// </summary>
            [RepositoryItem("3f6d0e2d-b5f5-40f1-be49-6d0697af3b36")]
            public virtual Ranorex.ButtonTag TargetLanguage
            {
                get
                {
                    return _targetlanguageInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The TargetLanguage item info.
            /// </summary>
            [RepositoryItemInfo("3f6d0e2d-b5f5-40f1-be49-6d0697af3b36")]
            public virtual RepoItemInfo TargetLanguageInfo
            {
                get
                {
                    return _targetlanguageInfo;
                }
            }

            /// <summary>
            /// The Testdatasource item.
            /// </summary>
            [RepositoryItem("7d912d6e-5904-41e0-8f40-e2031471e486")]
            public virtual Ranorex.ATag Testdatasource
            {
                get
                {
                    return _testdatasourceInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Testdatasource item info.
            /// </summary>
            [RepositoryItemInfo("7d912d6e-5904-41e0-8f40-e2031471e486")]
            public virtual RepoItemInfo TestdatasourceInfo
            {
                get
                {
                    return _testdatasourceInfo;
                }
            }

            /// <summary>
            /// The Obsidian item.
            /// </summary>
            [RepositoryItem("dab9a596-2928-4ae9-8c89-44d66746a098")]
            public virtual Ranorex.ATag Obsidian
            {
                get
                {
                    return _obsidianInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Obsidian item info.
            /// </summary>
            [RepositoryItemInfo("dab9a596-2928-4ae9-8c89-44d66746a098")]
            public virtual RepoItemInfo ObsidianInfo
            {
                get
                {
                    return _obsidianInfo;
                }
            }

            /// <summary>
            /// The ButtonTagOk item.
            /// </summary>
            [RepositoryItem("49d8bcad-39b4-4a3c-9b4c-789a59fd4c98")]
            public virtual Ranorex.ButtonTag ButtonTagOk
            {
                get
                {
                    return _buttontagokInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagOk item info.
            /// </summary>
            [RepositoryItemInfo("49d8bcad-39b4-4a3c-9b4c-789a59fd4c98")]
            public virtual RepoItemInfo ButtonTagOkInfo
            {
                get
                {
                    return _buttontagokInfo;
                }
            }
        }

        /// <summary>
        /// The FormLoginFolder folder.
        /// </summary>
        [RepositoryFolder("e052f3f2-476a-4593-9776-bbd6f2c9089e")]
        public partial class FormLoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _criteriatypeInfo;
            RepoItemInfo _criteria_type_updateInfo;
            RepoItemInfo _targetlanguagenamedcriteriInfo;
            RepoItemInfo _selectentirecontentInfo;
            RepoItemInfo _selectheadingtitleInfo;
            RepoItemInfo _selectquerybyfieldInfo;

            /// <summary>
            /// Creates a new FormLogin  folder.
            /// </summary>
            public FormLoginFolder(RepoGenBaseFolder parentFolder) :
                    base("FormLogin", "body/div[2]/div[1]/div[1]/div[3]", parentFolder, 30000, null, false, "e052f3f2-476a-4593-9776-bbd6f2c9089e", "")
            {
                _criteriatypeInfo = new RepoItemInfo(this, "CriteriaType", "div[1]/button[@title='Criteria Type']", 30000, null, "c6a5c153-91ea-4b83-903e-862ccf9763e5");
                _criteria_type_updateInfo = new RepoItemInfo(this, "Criteria_type_update", "div[1]/button[@class='btn btn-default dropdown-toggle drop-down-title float-right display-flex criteria-type']", 30000, null, "3d00fc68-aa46-43af-8cb8-f2cde8d1de62");
                _targetlanguagenamedcriteriInfo = new RepoItemInfo(this, "TargetLanguageNamedCriteri", "div[2]/button[@class='btn btn-default dropdown-toggle drop-down-title float-right display-flex target-language']", 30000, null, "887d2a6d-083c-4aa5-90e1-7d12fbcb7707");
                _selectentirecontentInfo = new RepoItemInfo(this, "SelectEntireContent", "?/?/ul/?/?/a[@innertext='Entire Content']", 30000, null, "2ba60631-b87f-46c1-b864-cf2cd8bf2973");
                _selectheadingtitleInfo = new RepoItemInfo(this, "SelectHeadingTitle", "?/?/ul/?/?/a[@innertext='Heading and Title']", 30000, null, "252dfb09-7e3a-4e00-b9f2-0bfcead000e9");
                _selectquerybyfieldInfo = new RepoItemInfo(this, "SelectQueryByField", "?/?/ul/?/?/a[@innertext='Query By Field']", 30000, null, "a5fd6f06-438b-4e0d-a1db-1b7931a1e02e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e052f3f2-476a-4593-9776-bbd6f2c9089e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e052f3f2-476a-4593-9776-bbd6f2c9089e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CriteriaType item.
            /// </summary>
            [RepositoryItem("c6a5c153-91ea-4b83-903e-862ccf9763e5")]
            public virtual Ranorex.Button CriteriaType
            {
                get
                {
                    return _criteriatypeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CriteriaType item info.
            /// </summary>
            [RepositoryItemInfo("c6a5c153-91ea-4b83-903e-862ccf9763e5")]
            public virtual RepoItemInfo CriteriaTypeInfo
            {
                get
                {
                    return _criteriatypeInfo;
                }
            }

            /// <summary>
            /// The Criteria_type_update item.
            /// </summary>
            [RepositoryItem("3d00fc68-aa46-43af-8cb8-f2cde8d1de62")]
            public virtual Ranorex.ButtonTag Criteria_type_update
            {
                get
                {
                    return _criteria_type_updateInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Criteria_type_update item info.
            /// </summary>
            [RepositoryItemInfo("3d00fc68-aa46-43af-8cb8-f2cde8d1de62")]
            public virtual RepoItemInfo Criteria_type_updateInfo
            {
                get
                {
                    return _criteria_type_updateInfo;
                }
            }

            /// <summary>
            /// The TargetLanguageNamedCriteri item.
            /// </summary>
            [RepositoryItem("887d2a6d-083c-4aa5-90e1-7d12fbcb7707")]
            public virtual Ranorex.ButtonTag TargetLanguageNamedCriteri
            {
                get
                {
                    return _targetlanguagenamedcriteriInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The TargetLanguageNamedCriteri item info.
            /// </summary>
            [RepositoryItemInfo("887d2a6d-083c-4aa5-90e1-7d12fbcb7707")]
            public virtual RepoItemInfo TargetLanguageNamedCriteriInfo
            {
                get
                {
                    return _targetlanguagenamedcriteriInfo;
                }
            }

            /// <summary>
            /// The SelectEntireContent item.
            /// </summary>
            [RepositoryItem("2ba60631-b87f-46c1-b864-cf2cd8bf2973")]
            public virtual Ranorex.ATag SelectEntireContent
            {
                get
                {
                    return _selectentirecontentInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SelectEntireContent item info.
            /// </summary>
            [RepositoryItemInfo("2ba60631-b87f-46c1-b864-cf2cd8bf2973")]
            public virtual RepoItemInfo SelectEntireContentInfo
            {
                get
                {
                    return _selectentirecontentInfo;
                }
            }

            /// <summary>
            /// The SelectHeadingTitle item.
            /// </summary>
            [RepositoryItem("252dfb09-7e3a-4e00-b9f2-0bfcead000e9")]
            public virtual Ranorex.ATag SelectHeadingTitle
            {
                get
                {
                    return _selectheadingtitleInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SelectHeadingTitle item info.
            /// </summary>
            [RepositoryItemInfo("252dfb09-7e3a-4e00-b9f2-0bfcead000e9")]
            public virtual RepoItemInfo SelectHeadingTitleInfo
            {
                get
                {
                    return _selectheadingtitleInfo;
                }
            }

            /// <summary>
            /// The SelectQueryByField item.
            /// </summary>
            [RepositoryItem("a5fd6f06-438b-4e0d-a1db-1b7931a1e02e")]
            public virtual Ranorex.ATag SelectQueryByField
            {
                get
                {
                    return _selectquerybyfieldInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SelectQueryByField item info.
            /// </summary>
            [RepositoryItemInfo("a5fd6f06-438b-4e0d-a1db-1b7931a1e02e")]
            public virtual RepoItemInfo SelectQueryByFieldInfo
            {
                get
                {
                    return _selectquerybyfieldInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
