///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NamedCriteria
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The QueryTool recording.
    /// </summary>
    [TestModule("5d40d386-f490-484a-9afd-007808987852", ModuleType.Recording, 1)]
    public partial class QueryTool : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NamedCriteriaRepository repository.
        /// </summary>
        public static NamedCriteriaRepository repo = NamedCriteriaRepository.Instance;

        static QueryTool instance = new QueryTool();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public QueryTool()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static QueryTool Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.QueryToolTab' at 57;3.", repo.ApplicationUnderTest.QueryToolTabInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.QueryToolTab.Click("57;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RawCriteriaQueryTool' at Center.", repo.ApplicationUnderTest.RawCriteriaQueryToolInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RawCriteriaQueryTool.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '\"Pizza\" AND \"Donut\"' with focus on 'ApplicationUnderTest.RawCriteriaQueryTool'.", repo.ApplicationUnderTest.RawCriteriaQueryToolInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RawCriteriaQueryTool.PressKeys("\"Pizza\" AND \"Donut\"");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.QueryNowQueryTool' at 55;19.", repo.ApplicationUnderTest.QueryNowQueryToolInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.QueryNowQueryTool.Click("55;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CriteriaTypeQueryTool' at 172;25.", repo.ApplicationUnderTest.CriteriaTypeQueryToolInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.CriteriaTypeQueryTool.Click("172;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.SelectEntireCriteriaContentType' at 102;19.", repo.ApplicationUnderTest.PaddingTop100Row.SelectEntireCriteriaContentTypeInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.PaddingTop100Row.SelectEntireCriteriaContentType.Click("102;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.QueryNowQueryTool' at 38;20.", repo.ApplicationUnderTest.QueryNowQueryToolInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.QueryNowQueryTool.Click("38;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TargetLanguageQueryTool' at 42;17.", repo.ApplicationUnderTest.TargetLanguageQueryToolInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.TargetLanguageQueryTool.Click("42;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.English' at 43;13.", repo.ApplicationUnderTest.EnglishInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.English.Click("43;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -619 units.", new RecordItemIndex(9));
            Mouse.ScrollWheel(-619);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 976 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(976);
            Delay.Milliseconds(400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatasourceQueryTool' at 58;23.", repo.ApplicationUnderTest.DatasourceQueryToolInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.DatasourceQueryTool.Click("58;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.Testdatasource' at 59;9.", repo.ApplicationUnderTest.PaddingTop100Row.TestdatasourceInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.PaddingTop100Row.Testdatasource.Click("59;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.QueryNowQueryTool' at 35;22.", repo.ApplicationUnderTest.QueryNowQueryToolInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.QueryNowQueryTool.Click("35;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatasourceQueryTool' at 120;15.", repo.ApplicationUnderTest.DatasourceQueryToolInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.DatasourceQueryTool.Click("120;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.Obsidian' at 106;13.", repo.ApplicationUnderTest.PaddingTop100Row.ObsidianInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.PaddingTop100Row.Obsidian.Click("106;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.QueryNowQueryTool' at 20;10.", repo.ApplicationUnderTest.QueryNowQueryToolInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.QueryNowQueryTool.Click("20;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNamedCriteria' at 76;9.", repo.ApplicationUnderTest.CreateNamedCriteriaInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.CreateNamedCriteria.Click("76;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NamedCriteriaName' at 539;21.", repo.ApplicationUnderTest.NamedCriteriaNameInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.NamedCriteriaName.Click("539;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Fast Food' with focus on 'ApplicationUnderTest.NamedCriteriaName'.", repo.ApplicationUnderTest.NamedCriteriaNameInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.NamedCriteriaName.PressKeys("Fast Food");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SaveNamedInQueryTool' at 23;13.", repo.ApplicationUnderTest.SaveNamedInQueryToolInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.SaveNamedInQueryTool.Click("23;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.Show' at 20;5.", repo.ApplicationUnderTest.PaddingTop100Row.ShowInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.PaddingTop100Row.Show.Click("20;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PreviewResults' at 53;17.", repo.ApplicationUnderTest.PreviewResultsInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.PreviewResults.Click("53;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CloseNamedCriteria' at 16;9.", repo.ApplicationUnderTest.CloseNamedCriteriaInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.CloseNamedCriteria.Click("16;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria'", repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteriaInfo, new ActionTimeout(5000), new RecordItemIndex(24));
            repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteriaInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria' at 15;3.", repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteriaInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.PaddingTop100Row.EditNamedCriteria.Click("15;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RawCriteriaQueryTool' at 333;19.", repo.ApplicationUnderTest.RawCriteriaQueryToolInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.RawCriteriaQueryTool.Click("333;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' {RShiftKey down}{\" down}{RShiftKey up}Dessert{RShiftKey down}\"{RShiftKey up}' with focus on 'ApplicationUnderTest.RawCriteriaQueryTool'.", repo.ApplicationUnderTest.RawCriteriaQueryToolInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.RawCriteriaQueryTool.PressKeys(" {RShiftKey down}{\" down}{RShiftKey up}Dessert{RShiftKey down}\"{RShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PreviewResults' at 43;22.", repo.ApplicationUnderTest.PreviewResultsInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.PreviewResults.Click("43;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SaveNamedCriteria' at 98;21.", repo.ApplicationUnderTest.SaveNamedCriteriaInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.SaveNamedCriteria.Click("98;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Delete' at 33;6.", repo.ApplicationUnderTest.DeleteInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.Delete.Click("33;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PaddingTop100Row.ButtonTagOk' at 19;18.", repo.ApplicationUnderTest.PaddingTop100Row.ButtonTagOkInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.PaddingTop100Row.ButtonTagOk.Click("19;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AdminUser' at 74;28.", repo.ApplicationUnderTest.AdminUserInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.AdminUser.Click("74;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ATagLogout' at 89;12.", repo.ApplicationUnderTest.ATagLogoutInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.ATagLogout.Click("89;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
