///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace LoginObsidian
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LoginObsidianRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f69fcabe-3d3c-49d1-94d5-8e10d5614587")]
    public partial class LoginObsidianRepository : RepoGenBaseFolder
    {
        static LoginObsidianRepository instance = new LoginObsidianRepository();
        LoginObsidianRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the LoginObsidianRepository element repository.
        /// </summary>
        [RepositoryFolder("f69fcabe-3d3c-49d1-94d5-8e10d5614587")]
        public static LoginObsidianRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LoginObsidianRepository() 
            : base("LoginObsidianRepository", "/", null, 0, false, "f69fcabe-3d3c-49d1-94d5-8e10d5614587", ".\\RepositoryImages\\LoginObsidianRepositoryf69fcabe.rximgres")
        {
            _applicationundertest = new LoginObsidianRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f69fcabe-3d3c-49d1-94d5-8e10d5614587")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("c9aeb153-65fc-4e2b-acf6-9fda92dce74d")]
        public virtual LoginObsidianRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class LoginObsidianRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("c9aeb153-65fc-4e2b-acf6-9fda92dce74d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            LoginObsidianRepositoryFolders.ContainerFolder _container;
            RepoItemInfo _useremailInfo;
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _commitInfo;
            RepoItemInfo _contextstudioInfo;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _contextdescriptionInfo;
            RepoItemInfo _ataglogoutInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='obsidian-staging.conde.io']", parentFolder, 30000, null, false, "c9aeb153-65fc-4e2b-acf6-9fda92dce74d", "")
            {
                _container = new LoginObsidianRepositoryFolders.ContainerFolder(this);
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "30aa3156-89d7-45ef-ba92-3c6e65088364");
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "948265b4-e204-4bbd-8b29-1ed57d84763f");
                _commitInfo = new RepoItemInfo(this, "Commit", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "5577d352-3b43-4eb3-b9d5-301da7285601");
                _contextstudioInfo = new RepoItemInfo(this, "ContextStudio", ".//h1[#'site_title']/a[@innertext='Context Studio']", 30000, null, "78a43905-d300-4f9b-8d7d-80f72604b884");
                _buttonInfo = new RepoItemInfo(this, "Button", "body/div[1]/div/div/div/div[2]/input[@type='button']", 30000, null, "502d2d8a-929e-4b6c-9bcc-fbee4c8bc39d");
                _closeInfo = new RepoItemInfo(this, "Close", "body/div[1]/div/div/div/div[2]/?/?/a[@innertext='Close']", 30000, null, "776b90fa-9729-4a76-8981-7638881ef85f");
                _contextdescriptionInfo = new RepoItemInfo(this, "ContextDescription", ".//input[#'context-description']", 30000, null, "83c8e62e-c090-4b2a-8252-f40bde12fbf3");
                _ataglogoutInfo = new RepoItemInfo(this, "ATagLogout", ".//div[#'myDropdown']/a[@innertext='  Logout']", 30000, null, "d1384c83-1531-44fb-8dad-d765ddce06ee");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c9aeb153-65fc-4e2b-acf6-9fda92dce74d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c9aeb153-65fc-4e2b-acf6-9fda92dce74d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("30aa3156-89d7-45ef-ba92-3c6e65088364")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("30aa3156-89d7-45ef-ba92-3c6e65088364")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("948265b4-e204-4bbd-8b29-1ed57d84763f")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("948265b4-e204-4bbd-8b29-1ed57d84763f")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("5577d352-3b43-4eb3-b9d5-301da7285601")]
            public virtual Ranorex.InputTag Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("5577d352-3b43-4eb3-b9d5-301da7285601")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }

            /// <summary>
            /// The ContextStudio item.
            /// </summary>
            [RepositoryItem("78a43905-d300-4f9b-8d7d-80f72604b884")]
            public virtual Ranorex.ATag ContextStudio
            {
                get
                {
                    return _contextstudioInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ContextStudio item info.
            /// </summary>
            [RepositoryItemInfo("78a43905-d300-4f9b-8d7d-80f72604b884")]
            public virtual RepoItemInfo ContextStudioInfo
            {
                get
                {
                    return _contextstudioInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("502d2d8a-929e-4b6c-9bcc-fbee4c8bc39d")]
            public virtual Ranorex.InputTag Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("502d2d8a-929e-4b6c-9bcc-fbee4c8bc39d")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("776b90fa-9729-4a76-8981-7638881ef85f")]
            public virtual Ranorex.ATag Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("776b90fa-9729-4a76-8981-7638881ef85f")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The ContextDescription item.
            /// </summary>
            [RepositoryItem("83c8e62e-c090-4b2a-8252-f40bde12fbf3")]
            public virtual Ranorex.InputTag ContextDescription
            {
                get
                {
                    return _contextdescriptionInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ContextDescription item info.
            /// </summary>
            [RepositoryItemInfo("83c8e62e-c090-4b2a-8252-f40bde12fbf3")]
            public virtual RepoItemInfo ContextDescriptionInfo
            {
                get
                {
                    return _contextdescriptionInfo;
                }
            }

            /// <summary>
            /// The ATagLogout item.
            /// </summary>
            [RepositoryItem("d1384c83-1531-44fb-8dad-d765ddce06ee")]
            public virtual Ranorex.ATag ATagLogout
            {
                get
                {
                    return _ataglogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagLogout item info.
            /// </summary>
            [RepositoryItemInfo("d1384c83-1531-44fb-8dad-d765ddce06ee")]
            public virtual RepoItemInfo ATagLogoutInfo
            {
                get
                {
                    return _ataglogoutInfo;
                }
            }

            /// <summary>
            /// The Container folder.
            /// </summary>
            [RepositoryFolder("9c190b5e-4c7b-44ef-9b59-819c571fd66e")]
            public virtual LoginObsidianRepositoryFolders.ContainerFolder Container
            {
                get { return _container; }
            }
        }

        /// <summary>
        /// The ContainerFolder folder.
        /// </summary>
        [RepositoryFolder("9c190b5e-4c7b-44ef-9b59-819c571fd66e")]
        public partial class ContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _priyankarameshInfo;
            RepoItemInfo _automotiveInfo;
            RepoItemInfo _fafasearchInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _classificationsInfo;
            RepoItemInfo _subclassificationsInfo;
            RepoItemInfo _autobodystylesInfo;
            RepoItemInfo _clearfilterInfo;
            RepoItemInfo _obzay56Info;
            RepoItemInfo _womenbeautyprodutsInfo;
            RepoItemInfo _editInfo;
            RepoItemInfo _showInfo;

            /// <summary>
            /// Creates a new Container  folder.
            /// </summary>
            public ContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("Container", "body/div", parentFolder, 30000, null, false, "9c190b5e-4c7b-44ef-9b59-819c571fd66e", "")
            {
                _priyankarameshInfo = new RepoItemInfo(this, "PriyankaRamesh", "div[1]//button[@innertext='Priyanka Ramesh ']", 30000, null, "d406bc9c-f621-4b9c-bd81-e8343b0c7933");
                _automotiveInfo = new RepoItemInfo(this, "Automotive", "div[2]/div[1]/div/div[1]/?/?/ul/li[2]/a[@innertext='Automotive']", 30000, null, "8322d83b-13be-4bad-8f6f-15c89ea943bc");
                _fafasearchInfo = new RepoItemInfo(this, "FaFaSearch", "div[2]/div[1]/div/div[1]/div[1]/?/?/i", 30000, null, "6d2062ba-9272-4fe8-9621-e037a9175f9c");
                _searchInfo = new RepoItemInfo(this, "Search", "div[2]/div[1]/div/div[1]/div[1]/?/?/input[@name='search']", 30000, null, "d6f8d75e-8556-4b0f-b321-dba5bd213ce1");
                _classificationsInfo = new RepoItemInfo(this, "Classifications", "div[2]/div[1]/div/div[1]/div[2]/button[@innertext='Classifications']", 30000, null, "d4072f08-56f9-4c29-bae0-c10dd79aa521");
                _subclassificationsInfo = new RepoItemInfo(this, "SubClassifications", "div[2]/div[1]/div/div[1]/div[3]/button[@innertext='Sub-Classifications ']", 30000, null, "b000ec6a-f913-4c7e-868f-0a518a731774");
                _autobodystylesInfo = new RepoItemInfo(this, "AutoBodyStyles", "div[2]/div[1]/div/div[1]/div[3]/ul/li[1]/a[@innertext='Auto Body Styles']", 30000, null, "91a8ffa8-7fdc-45bc-a353-ccd0dfc69903");
                _clearfilterInfo = new RepoItemInfo(this, "ClearFilter", "div[2]/div[1]/div/div[3]/?/?/a[@innertext='Clear Filter']", 30000, null, "15ff1ce7-f18c-402f-8cf4-13a798bc55cb");
                _obzay56Info = new RepoItemInfo(this, "OBZAY56", "div[2]/div[2]/?/?/table/tbody/tr[1]/td[1]/?/?/a[@innertext='OBZAY56']", 30000, null, "475fc72c-b780-4813-8bed-790a0bca5716");
                _womenbeautyprodutsInfo = new RepoItemInfo(this, "WomenBeautyProduts", "div[2]/div[2]/?/?/table/tbody/tr[1]/td[2]/?/?/div/span[1]/a[@innertext='Women beauty Produts']", 30000, null, "2ad33d06-80af-4e38-97cb-44764366e77d");
                _editInfo = new RepoItemInfo(this, "Edit", "div[2]/div[2]/?/?/table/tbody/tr[1]/td[6]/span[@innertext=' /  / ']/a[@innertext='Edit']", 30000, null, "f2215fe1-521c-4985-9b80-ada8c5f27d99");
                _showInfo = new RepoItemInfo(this, "Show", "div[2]/div[2]/?/?/table/tbody/tr[1]/td[6]/span[@innertext=' /  / ']/a[@innertext='Show']", 30000, null, "0d542a7f-c0a3-4b53-93a7-aa4a0372889e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c190b5e-4c7b-44ef-9b59-819c571fd66e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c190b5e-4c7b-44ef-9b59-819c571fd66e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PriyankaRamesh item.
            /// </summary>
            [RepositoryItem("d406bc9c-f621-4b9c-bd81-e8343b0c7933")]
            public virtual Ranorex.ButtonTag PriyankaRamesh
            {
                get
                {
                    return _priyankarameshInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The PriyankaRamesh item info.
            /// </summary>
            [RepositoryItemInfo("d406bc9c-f621-4b9c-bd81-e8343b0c7933")]
            public virtual RepoItemInfo PriyankaRameshInfo
            {
                get
                {
                    return _priyankarameshInfo;
                }
            }

            /// <summary>
            /// The Automotive item.
            /// </summary>
            [RepositoryItem("8322d83b-13be-4bad-8f6f-15c89ea943bc")]
            public virtual Ranorex.ATag Automotive
            {
                get
                {
                    return _automotiveInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Automotive item info.
            /// </summary>
            [RepositoryItemInfo("8322d83b-13be-4bad-8f6f-15c89ea943bc")]
            public virtual RepoItemInfo AutomotiveInfo
            {
                get
                {
                    return _automotiveInfo;
                }
            }

            /// <summary>
            /// The FaFaSearch item.
            /// </summary>
            [RepositoryItem("6d2062ba-9272-4fe8-9621-e037a9175f9c")]
            public virtual Ranorex.ITag FaFaSearch
            {
                get
                {
                    return _fafasearchInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaSearch item info.
            /// </summary>
            [RepositoryItemInfo("6d2062ba-9272-4fe8-9621-e037a9175f9c")]
            public virtual RepoItemInfo FaFaSearchInfo
            {
                get
                {
                    return _fafasearchInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("d6f8d75e-8556-4b0f-b321-dba5bd213ce1")]
            public virtual Ranorex.InputTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("d6f8d75e-8556-4b0f-b321-dba5bd213ce1")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The Classifications item.
            /// </summary>
            [RepositoryItem("d4072f08-56f9-4c29-bae0-c10dd79aa521")]
            public virtual Ranorex.ButtonTag Classifications
            {
                get
                {
                    return _classificationsInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Classifications item info.
            /// </summary>
            [RepositoryItemInfo("d4072f08-56f9-4c29-bae0-c10dd79aa521")]
            public virtual RepoItemInfo ClassificationsInfo
            {
                get
                {
                    return _classificationsInfo;
                }
            }

            /// <summary>
            /// The SubClassifications item.
            /// </summary>
            [RepositoryItem("b000ec6a-f913-4c7e-868f-0a518a731774")]
            public virtual Ranorex.ButtonTag SubClassifications
            {
                get
                {
                    return _subclassificationsInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubClassifications item info.
            /// </summary>
            [RepositoryItemInfo("b000ec6a-f913-4c7e-868f-0a518a731774")]
            public virtual RepoItemInfo SubClassificationsInfo
            {
                get
                {
                    return _subclassificationsInfo;
                }
            }

            /// <summary>
            /// The AutoBodyStyles item.
            /// </summary>
            [RepositoryItem("91a8ffa8-7fdc-45bc-a353-ccd0dfc69903")]
            public virtual Ranorex.ATag AutoBodyStyles
            {
                get
                {
                    return _autobodystylesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AutoBodyStyles item info.
            /// </summary>
            [RepositoryItemInfo("91a8ffa8-7fdc-45bc-a353-ccd0dfc69903")]
            public virtual RepoItemInfo AutoBodyStylesInfo
            {
                get
                {
                    return _autobodystylesInfo;
                }
            }

            /// <summary>
            /// The ClearFilter item.
            /// </summary>
            [RepositoryItem("15ff1ce7-f18c-402f-8cf4-13a798bc55cb")]
            public virtual Ranorex.ATag ClearFilter
            {
                get
                {
                    return _clearfilterInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ClearFilter item info.
            /// </summary>
            [RepositoryItemInfo("15ff1ce7-f18c-402f-8cf4-13a798bc55cb")]
            public virtual RepoItemInfo ClearFilterInfo
            {
                get
                {
                    return _clearfilterInfo;
                }
            }

            /// <summary>
            /// The OBZAY56 item.
            /// </summary>
            [RepositoryItem("475fc72c-b780-4813-8bed-790a0bca5716")]
            public virtual Ranorex.ATag OBZAY56
            {
                get
                {
                    return _obzay56Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OBZAY56 item info.
            /// </summary>
            [RepositoryItemInfo("475fc72c-b780-4813-8bed-790a0bca5716")]
            public virtual RepoItemInfo OBZAY56Info
            {
                get
                {
                    return _obzay56Info;
                }
            }

            /// <summary>
            /// The WomenBeautyProduts item.
            /// </summary>
            [RepositoryItem("2ad33d06-80af-4e38-97cb-44764366e77d")]
            public virtual Ranorex.ATag WomenBeautyProduts
            {
                get
                {
                    return _womenbeautyprodutsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The WomenBeautyProduts item info.
            /// </summary>
            [RepositoryItemInfo("2ad33d06-80af-4e38-97cb-44764366e77d")]
            public virtual RepoItemInfo WomenBeautyProdutsInfo
            {
                get
                {
                    return _womenbeautyprodutsInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("f2215fe1-521c-4985-9b80-ada8c5f27d99")]
            public virtual Ranorex.ATag Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("f2215fe1-521c-4985-9b80-ada8c5f27d99")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The Show item.
            /// </summary>
            [RepositoryItem("0d542a7f-c0a3-4b53-93a7-aa4a0372889e")]
            public virtual Ranorex.ATag Show
            {
                get
                {
                    return _showInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Show item info.
            /// </summary>
            [RepositoryItemInfo("0d542a7f-c0a3-4b53-93a7-aa4a0372889e")]
            public virtual RepoItemInfo ShowInfo
            {
                get
                {
                    return _showInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
