///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LoginObsidian
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginScenarios recording.
    /// </summary>
    [TestModule("3a8db3df-27d0-4055-a6e7-baace9392cbc", ModuleType.Recording, 1)]
    public partial class LoginScenarios : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LoginObsidianRepository repository.
        /// </summary>
        public static LoginObsidianRepository repo = LoginObsidianRepository.Instance;

        static LoginScenarios instance = new LoginScenarios();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginScenarios()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginScenarios Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserEmail' at 82;18.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.UserEmail.Click("82;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.UserEmail.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 93;16.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("93;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}{Back}{Back}' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.UserEmail.PressKeys("{Back}{Back}{Back}{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'obs-admin@condenast' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.UserEmail.PressKeys("obs-admin@condenast");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 59;20.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("59;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserEmail' at 165;19.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.UserEmail.Click("165;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.com' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.UserEmail.PressKeys(".com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 96;23.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("96;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserPassword' at 68;24.", repo.ApplicationUnderTest.UserPasswordInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.UserPassword.Click("68;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password' with focus on 'ApplicationUnderTest.UserPassword'.", repo.ApplicationUnderTest.UserPasswordInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.UserPassword.PressKeys("password");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 80;25.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("80;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Logout' at 33;14.", repo.ApplicationUnderTest.LogoutInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Logout.Click("33;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Container.Google' at 28;7.", repo.ApplicationUnderTest.Container.GoogleInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.Container.Google.Click("28;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Container.PriyankaRamesh' at 98;21.", repo.ApplicationUnderTest.Container.PriyankaRameshInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.Container.PriyankaRamesh.Click("98;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ATagLogout' at 80;11.", repo.ApplicationUnderTest.ATagLogoutInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.ATagLogout.Click("80;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ForgotPassword' at 280;5.", repo.ApplicationUnderTest.ForgotPasswordInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.ForgotPassword.Click("280;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserEmail' at 248;21.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.UserEmail.Click("248;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'priyanka_ramesh@condenast.com' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.UserEmail.PressKeys("priyanka_ramesh@condenast.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 204;26.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("204;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ForgotPassword' at Center.", repo.ApplicationUnderTest.ForgotPasswordInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.ForgotPassword.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserEmail' at 90;19.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.UserEmail.Click("90;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'NewUSer' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.UserEmail.PressKeys("NewUSer");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 105;58.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("105;58");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserEmail' at 69;23.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.UserEmail.Click("69;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '@condenast' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.UserEmail.PressKeys("@condenast");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 81;19.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("81;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ObsidianStagingCondeIoUsersPassword.Back' at 23;21.", repo.ObsidianStagingCondeIoUsersPassword.BackInfo, new RecordItemIndex(27));
            repo.ObsidianStagingCondeIoUsersPassword.Back.Click("23;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.com' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press(".com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 167;24.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("167;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ObsidianStagingCondeIoUsersPassword.Back' at 22;14.", repo.ObsidianStagingCondeIoUsersPassword.BackInfo, new RecordItemIndex(30));
            repo.ObsidianStagingCondeIoUsersPassword.Back.Click("22;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.UserEmail' at 203;25.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.UserEmail.MoveTo("203;25");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.UserEmail' at 6;25.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.UserEmail.MoveTo("6;25");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'priyanka_ramesh@condenast.com' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(34));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("priyanka_ramesh@condenast.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResetPasswordLink' at 122;22.", repo.ApplicationUnderTest.ResetPasswordLinkInfo, new RecordItemIndex(35));
            repo.ApplicationUnderTest.ResetPasswordLink.Click("122;22");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
