///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PagelistCreation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PagelistFunctions recording.
    /// </summary>
    [TestModule("06b2bba4-f6fa-4019-8c9f-d77c8b0e6e18", ModuleType.Recording, 1)]
    public partial class PagelistFunctions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PagelistCreationRepository repository.
        /// </summary>
        public static PagelistCreationRepository repo = PagelistCreationRepository.Instance;

        static PagelistFunctions instance = new PagelistFunctions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PagelistFunctions()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PagelistFunctions Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.UserEmail' at 36;18.", repo.ContextStudio.UserEmailInfo, new RecordItemIndex(0));
            repo.ContextStudio.UserEmail.Click("36;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'priyanka{RShiftKey down}_{RShiftKey up}ramesh{RShiftKey down}@{RShiftKey up}condenast.com' with focus on 'ContextStudio.UserEmail'.", repo.ContextStudio.UserEmailInfo, new RecordItemIndex(1));
            repo.ContextStudio.UserEmail.PressKeys("priyanka{RShiftKey down}_{RShiftKey up}ramesh{RShiftKey down}@{RShiftKey up}condenast.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.UserPassword' at 68;28.", repo.ContextStudio.UserPasswordInfo, new RecordItemIndex(2));
            repo.ContextStudio.UserPassword.Click("68;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'obsidian' with focus on 'ContextStudio.UserPassword'.", repo.ContextStudio.UserPasswordInfo, new RecordItemIndex(3));
            repo.ContextStudio.UserPassword.PressKeys("obsidian");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.LogIn' at 79;-1.", repo.ContextStudio.LogInInfo, new RecordItemIndex(4));
            repo.ContextStudio.LogIn.Click("79;-1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ContextStudio_ToUserPortal' at 76;13.", repo.ContextStudio.ContextStudio_ToUserPortalInfo, new RecordItemIndex(5));
            repo.ContextStudio.ContextStudio_ToUserPortal.Click("76;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.PAGELISTS_tab' at 40;5.", repo.ContextStudio.PAGELISTS_tabInfo, new RecordItemIndex(6));
            repo.ContextStudio.PAGELISTS_tab.Click("40;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.CreatePageList' at 12;21.", repo.ContextStudio.Container.CreatePageListInfo, new RecordItemIndex(7));
            repo.ContextStudio.Container.CreatePageList.Click("12;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.PageListName' at 554;28.", repo.ContextStudio.PageListNameInfo, new RecordItemIndex(8));
            repo.ContextStudio.PageListName.Click("554;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Pagelist urls' with focus on 'ContextStudio.PageListName'.", repo.ContextStudio.PageListNameInfo, new RecordItemIndex(9));
            repo.ContextStudio.PageListName.PressKeys("Pagelist urls");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' urls' with focus on 'ContextStudio.PageListName'.", repo.ContextStudio.PageListNameInfo, new RecordItemIndex(10));
            //repo.ContextStudio.PageListName.PressKeys(" urls");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.PageListPath' at 348;25.", repo.ContextStudio.PageListPathInfo, new RecordItemIndex(11));
            repo.ContextStudio.PageListPath.Click("348;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 's3://obs-vendor-dev/Reg_test' with focus on 'ContextStudio.PageListPath'.", repo.ContextStudio.PageListPathInfo, new RecordItemIndex(12));
            repo.ContextStudio.PageListPath.PressKeys("s3://obs-vendor-dev/Reg_test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.SavePageList' at 77;13.", repo.ContextStudio.Container.SavePageListInfo, new RecordItemIndex(13));
            repo.ContextStudio.Container.SavePageList.Click("77;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ShowPagelist' at 10;5.", repo.ContextStudio.ShowPagelistInfo, new RecordItemIndex(14));
            repo.ContextStudio.ShowPagelist.Click("10;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Close' at 22;4.", repo.ContextStudio.CloseInfo, new RecordItemIndex(15));
            repo.ContextStudio.Close.Click("22;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.EditPagelist' at 12;10.", repo.ContextStudio.EditPagelistInfo, new RecordItemIndex(16));
            repo.ContextStudio.EditPagelist.Click("12;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.PageDescription' at 351;22.", repo.ContextStudio.PageDescriptionInfo, new RecordItemIndex(17));
            repo.ContextStudio.PageDescription.Click("351;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'pagelist' with focus on 'ContextStudio.PageDescription'.", repo.ContextStudio.PageDescriptionInfo, new RecordItemIndex(18));
            repo.ContextStudio.PageDescription.PressKeys("pagelist");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.PageListName' at 123;24.", repo.ContextStudio.PageListNameInfo, new RecordItemIndex(19));
            repo.ContextStudio.PageListName.Click("123;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ContextStudio.PageListName'.", repo.ContextStudio.PageListNameInfo, new RecordItemIndex(20));
            repo.ContextStudio.PageListName.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.SavePageList' at 64;21.", repo.ContextStudio.Container.SavePageListInfo, new RecordItemIndex(21));
            repo.ContextStudio.Container.SavePageList.Click("64;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.Text' at 557;33.", repo.ContextStudio.Container.TextInfo, new RecordItemIndex(22));
            repo.ContextStudio.Container.Text.Click("557;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'pagelist' with focus on 'ContextStudio.Container.Text'.", repo.ContextStudio.Container.TextInfo, new RecordItemIndex(23));
            repo.ContextStudio.Container.Text.PressKeys("pagelist");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.ClearSearch' at 62;6.", repo.ContextStudio.Container.ClearSearchInfo, new RecordItemIndex(24));
            repo.ContextStudio.Container.ClearSearch.Click("62;6");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.UserMenu' at 90;30.", repo.ContextStudio.Container.UserMenuInfo, new RecordItemIndex(25));
            //repo.ContextStudio.Container.UserMenu.Click("90;30");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio.Logout' at 81;16.", repo.ContextStudio.LogoutInfo, new RecordItemIndex(26));
            //repo.ContextStudio.Logout.MoveTo("81;16");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio.Logout' at 81;16.", repo.ContextStudio.LogoutInfo, new RecordItemIndex(27));
            //repo.ContextStudio.Logout.MoveTo("81;16");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
