///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PagelistCreation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PagelistCreationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1a5f8a4a-3208-4b3b-87fb-4af87796a57a")]
    public partial class PagelistCreationRepository : RepoGenBaseFolder
    {
        static PagelistCreationRepository instance = new PagelistCreationRepository();
        PagelistCreationRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        PagelistCreationRepositoryFolders.ContextStudioAppFolder _contextstudio;

        /// <summary>
        /// Gets the singleton class instance representing the PagelistCreationRepository element repository.
        /// </summary>
        [RepositoryFolder("1a5f8a4a-3208-4b3b-87fb-4af87796a57a")]
        public static PagelistCreationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PagelistCreationRepository() 
            : base("PagelistCreationRepository", "/", null, 0, false, "1a5f8a4a-3208-4b3b-87fb-4af87796a57a", ".\\RepositoryImages\\PagelistCreationRepository1a5f8a4a.rximgres")
        {
            _applicationundertest = new PagelistCreationRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _contextstudio = new PagelistCreationRepositoryFolders.ContextStudioAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1a5f8a4a-3208-4b3b-87fb-4af87796a57a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("10fe921c-63a8-4019-9c9b-5f82289a97f4")]
        public virtual PagelistCreationRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ContextStudio folder.
        /// </summary>
        [RepositoryFolder("7aaee0d6-60f1-4c57-93c7-47cefebe5633")]
        public virtual PagelistCreationRepositoryFolders.ContextStudioAppFolder ContextStudio
        {
            get { return _contextstudio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PagelistCreationRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("10fe921c-63a8-4019-9c9b-5f82289a97f4")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _deletepagelistInfo;
            RepoItemInfo _deletepagelistselectionInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='obsidian-staging.conde.io']", parentFolder, 30000, null, false, "10fe921c-63a8-4019-9c9b-5f82289a97f4", "")
            {
                _deletepagelistInfo = new RepoItemInfo(this, "DeletePageList", ".//table/tbody/tr[1]/td[5]/span[@innertext>' /                      /']/a[@innertext='Delete']", 30000, null, "323703c5-e4a7-461a-b961-e3ffd64e4f13");
                _deletepagelistselectionInfo = new RepoItemInfo(this, "DeletePagelistSelection", ".//div[#'confirmPageListDelete']//button[@innertext='Ok']", 30000, null, "6595cb6d-4716-4440-a397-e9c2fc169dd3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10fe921c-63a8-4019-9c9b-5f82289a97f4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10fe921c-63a8-4019-9c9b-5f82289a97f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DeletePageList item.
            /// </summary>
            [RepositoryItem("323703c5-e4a7-461a-b961-e3ffd64e4f13")]
            public virtual Ranorex.ATag DeletePageList
            {
                get
                {
                    return _deletepagelistInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DeletePageList item info.
            /// </summary>
            [RepositoryItemInfo("323703c5-e4a7-461a-b961-e3ffd64e4f13")]
            public virtual RepoItemInfo DeletePageListInfo
            {
                get
                {
                    return _deletepagelistInfo;
                }
            }

            /// <summary>
            /// The DeletePagelistSelection item.
            /// </summary>
            [RepositoryItem("6595cb6d-4716-4440-a397-e9c2fc169dd3")]
            public virtual Ranorex.ButtonTag DeletePagelistSelection
            {
                get
                {
                    return _deletepagelistselectionInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The DeletePagelistSelection item info.
            /// </summary>
            [RepositoryItemInfo("6595cb6d-4716-4440-a397-e9c2fc169dd3")]
            public virtual RepoItemInfo DeletePagelistSelectionInfo
            {
                get
                {
                    return _deletepagelistselectionInfo;
                }
            }
        }

        /// <summary>
        /// The ContextStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("7aaee0d6-60f1-4c57-93c7-47cefebe5633")]
        public partial class ContextStudioAppFolder : RepoGenBaseFolder
        {
            PagelistCreationRepositoryFolders.ContainerFolder _container;
            RepoItemInfo _useremailInfo;
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _contextstudio_touserportalInfo;
            RepoItemInfo _pagelists_tabInfo;
            RepoItemInfo _pagelistnameInfo;
            RepoItemInfo _pagelistpathInfo;
            RepoItemInfo _showpagelistInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _editpagelistInfo;
            RepoItemInfo _pagedescriptionInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new ContextStudio  folder.
            /// </summary>
            public ContextStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContextStudio", "/dom[@domain='obsidian-staging.conde.io']", parentFolder, 30000, null, false, "7aaee0d6-60f1-4c57-93c7-47cefebe5633", "")
            {
                _container = new PagelistCreationRepositoryFolders.ContainerFolder(this);
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "2b7c676a-e18e-4c3a-82d2-ea5a07d10b8b");
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "5e5951b8-9112-4474-82da-7cb3656a48d2");
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "ab60b0e2-d43d-4c1d-8672-1c3c1981ed34");
                _contextstudio_touserportalInfo = new RepoItemInfo(this, "ContextStudio_ToUserPortal", ".//h1[#'site_title']/a[@innertext='Context Studio']", 30000, null, "71f0c35e-5d34-4ec5-9cdd-d3fbb82af3ef");
                _pagelists_tabInfo = new RepoItemInfo(this, "PAGELISTS_tab", ".//div[#'myTopnav']/a[@innertext='PAGE LISTS']", 30000, null, "fec1b489-1ba2-48a4-bd68-ffc88d7548b0");
                _pagelistnameInfo = new RepoItemInfo(this, "PageListName", ".//input[#'page_name']", 30000, null, "7758e0f7-0023-438d-8ef8-498ee09d552f");
                _pagelistpathInfo = new RepoItemInfo(this, "PageListPath", ".//input[#'page_path']", 30000, null, "298ebe4f-0965-408b-9d2b-3d31fe453da8");
                _showpagelistInfo = new RepoItemInfo(this, "ShowPagelist", ".//table/tbody/tr[1]/td[5]/span[@innertext>' /                      /']/a[@innertext='Show']", 30000, null, "adac4066-76ea-4467-b90b-95d7f35734da");
                _closeInfo = new RepoItemInfo(this, "Close", "body/div[1]//a[@innertext='Close']", 30000, null, "93f093b1-f513-45f5-9531-43eb7d1e0bb0");
                _editpagelistInfo = new RepoItemInfo(this, "EditPagelist", ".//table/tbody/tr[1]/td[5]/span[@innertext>' /                      /']/a[@innertext='Edit']", 30000, null, "b8b107e8-d688-4157-a7ae-0f7ed45efd29");
                _pagedescriptionInfo = new RepoItemInfo(this, "PageDescription", ".//input[#'page_description']", 30000, null, "e4f37a23-9b29-430a-a598-2b980f083f42");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[#'myDropdown']/a[@innertext='  Logout']", 30000, null, "9a55dbe4-d576-4a0d-b8b8-a04a1869d5be");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7aaee0d6-60f1-4c57-93c7-47cefebe5633")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7aaee0d6-60f1-4c57-93c7-47cefebe5633")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("2b7c676a-e18e-4c3a-82d2-ea5a07d10b8b")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("2b7c676a-e18e-4c3a-82d2-ea5a07d10b8b")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("5e5951b8-9112-4474-82da-7cb3656a48d2")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("5e5951b8-9112-4474-82da-7cb3656a48d2")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("ab60b0e2-d43d-4c1d-8672-1c3c1981ed34")]
            public virtual Ranorex.InputTag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("ab60b0e2-d43d-4c1d-8672-1c3c1981ed34")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The ContextStudio_ToUserPortal item.
            /// </summary>
            [RepositoryItem("71f0c35e-5d34-4ec5-9cdd-d3fbb82af3ef")]
            public virtual Ranorex.ATag ContextStudio_ToUserPortal
            {
                get
                {
                    return _contextstudio_touserportalInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ContextStudio_ToUserPortal item info.
            /// </summary>
            [RepositoryItemInfo("71f0c35e-5d34-4ec5-9cdd-d3fbb82af3ef")]
            public virtual RepoItemInfo ContextStudio_ToUserPortalInfo
            {
                get
                {
                    return _contextstudio_touserportalInfo;
                }
            }

            /// <summary>
            /// The PAGELISTS_tab item.
            /// </summary>
            [RepositoryItem("fec1b489-1ba2-48a4-bd68-ffc88d7548b0")]
            public virtual Ranorex.ATag PAGELISTS_tab
            {
                get
                {
                    return _pagelists_tabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PAGELISTS_tab item info.
            /// </summary>
            [RepositoryItemInfo("fec1b489-1ba2-48a4-bd68-ffc88d7548b0")]
            public virtual RepoItemInfo PAGELISTS_tabInfo
            {
                get
                {
                    return _pagelists_tabInfo;
                }
            }

            /// <summary>
            /// The PageListName item.
            /// </summary>
            [RepositoryItem("7758e0f7-0023-438d-8ef8-498ee09d552f")]
            public virtual Ranorex.InputTag PageListName
            {
                get
                {
                    return _pagelistnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PageListName item info.
            /// </summary>
            [RepositoryItemInfo("7758e0f7-0023-438d-8ef8-498ee09d552f")]
            public virtual RepoItemInfo PageListNameInfo
            {
                get
                {
                    return _pagelistnameInfo;
                }
            }

            /// <summary>
            /// The PageListPath item.
            /// </summary>
            [RepositoryItem("298ebe4f-0965-408b-9d2b-3d31fe453da8")]
            public virtual Ranorex.InputTag PageListPath
            {
                get
                {
                    return _pagelistpathInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PageListPath item info.
            /// </summary>
            [RepositoryItemInfo("298ebe4f-0965-408b-9d2b-3d31fe453da8")]
            public virtual RepoItemInfo PageListPathInfo
            {
                get
                {
                    return _pagelistpathInfo;
                }
            }

            /// <summary>
            /// The ShowPagelist item.
            /// </summary>
            [RepositoryItem("adac4066-76ea-4467-b90b-95d7f35734da")]
            public virtual Ranorex.ATag ShowPagelist
            {
                get
                {
                    return _showpagelistInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ShowPagelist item info.
            /// </summary>
            [RepositoryItemInfo("adac4066-76ea-4467-b90b-95d7f35734da")]
            public virtual RepoItemInfo ShowPagelistInfo
            {
                get
                {
                    return _showpagelistInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("93f093b1-f513-45f5-9531-43eb7d1e0bb0")]
            public virtual Ranorex.ATag Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("93f093b1-f513-45f5-9531-43eb7d1e0bb0")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The EditPagelist item.
            /// </summary>
            [RepositoryItem("b8b107e8-d688-4157-a7ae-0f7ed45efd29")]
            public virtual Ranorex.ATag EditPagelist
            {
                get
                {
                    return _editpagelistInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EditPagelist item info.
            /// </summary>
            [RepositoryItemInfo("b8b107e8-d688-4157-a7ae-0f7ed45efd29")]
            public virtual RepoItemInfo EditPagelistInfo
            {
                get
                {
                    return _editpagelistInfo;
                }
            }

            /// <summary>
            /// The PageDescription item.
            /// </summary>
            [RepositoryItem("e4f37a23-9b29-430a-a598-2b980f083f42")]
            public virtual Ranorex.InputTag PageDescription
            {
                get
                {
                    return _pagedescriptionInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PageDescription item info.
            /// </summary>
            [RepositoryItemInfo("e4f37a23-9b29-430a-a598-2b980f083f42")]
            public virtual RepoItemInfo PageDescriptionInfo
            {
                get
                {
                    return _pagedescriptionInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("9a55dbe4-d576-4a0d-b8b8-a04a1869d5be")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("9a55dbe4-d576-4a0d-b8b8-a04a1869d5be")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Container folder.
            /// </summary>
            [RepositoryFolder("5f03dc41-d99c-47c2-9df7-6bb6b8feaa64")]
            public virtual PagelistCreationRepositoryFolders.ContainerFolder Container
            {
                get { return _container; }
            }
        }

        /// <summary>
        /// The ContainerFolder folder.
        /// </summary>
        [RepositoryFolder("5f03dc41-d99c-47c2-9df7-6bb6b8feaa64")]
        public partial class ContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usermenuInfo;
            RepoItemInfo _clearsearchInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _savepagelistInfo;
            RepoItemInfo _createpagelistInfo;

            /// <summary>
            /// Creates a new Container  folder.
            /// </summary>
            public ContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("Container", "body/div", parentFolder, 30000, null, false, "5f03dc41-d99c-47c2-9df7-6bb6b8feaa64", "")
            {
                _usermenuInfo = new RepoItemInfo(this, "UserMenu", ".//button[@innertext='Priyanka Ramesh ']", 30000, null, "66a780b9-cab2-464f-91eb-1461d6c27f73");
                _clearsearchInfo = new RepoItemInfo(this, "ClearSearch", "div[2]/div[1]/?/?/span/a[@innertext='Clear Search']", 30000, null, "14857b1d-8017-4556-9159-20e37b3f1000");
                _textInfo = new RepoItemInfo(this, "Text", "div[2]/div[1]/div/div[1]/input[@type='text']", 30000, null, "4e87e81a-101c-42d7-9163-8f3b210f2540");
                _savepagelistInfo = new RepoItemInfo(this, "SavePageList", "div/div/div/div[2]/input[@type='button' and @class='action-button margin-right-10 float-right save-page-list']", 30000, null, "d8b58cf0-0682-46a6-93fb-ec7fa186c59e");
                _createpagelistInfo = new RepoItemInfo(this, "CreatePageList", "div/div/div/div[2]/input[@type='button' and @class='action-button float-right']", 30000, null, "ecaa715d-f249-4bd9-be61-d9400594bf8e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5f03dc41-d99c-47c2-9df7-6bb6b8feaa64")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5f03dc41-d99c-47c2-9df7-6bb6b8feaa64")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserMenu item.
            /// </summary>
            [RepositoryItem("66a780b9-cab2-464f-91eb-1461d6c27f73")]
            public virtual Ranorex.ButtonTag UserMenu
            {
                get
                {
                    return _usermenuInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The UserMenu item info.
            /// </summary>
            [RepositoryItemInfo("66a780b9-cab2-464f-91eb-1461d6c27f73")]
            public virtual RepoItemInfo UserMenuInfo
            {
                get
                {
                    return _usermenuInfo;
                }
            }

            /// <summary>
            /// The ClearSearch item.
            /// </summary>
            [RepositoryItem("14857b1d-8017-4556-9159-20e37b3f1000")]
            public virtual Ranorex.ATag ClearSearch
            {
                get
                {
                    return _clearsearchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ClearSearch item info.
            /// </summary>
            [RepositoryItemInfo("14857b1d-8017-4556-9159-20e37b3f1000")]
            public virtual RepoItemInfo ClearSearchInfo
            {
                get
                {
                    return _clearsearchInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("4e87e81a-101c-42d7-9163-8f3b210f2540")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("4e87e81a-101c-42d7-9163-8f3b210f2540")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The SavePageList item.
            /// </summary>
            [RepositoryItem("d8b58cf0-0682-46a6-93fb-ec7fa186c59e")]
            public virtual Ranorex.InputTag SavePageList
            {
                get
                {
                    return _savepagelistInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SavePageList item info.
            /// </summary>
            [RepositoryItemInfo("d8b58cf0-0682-46a6-93fb-ec7fa186c59e")]
            public virtual RepoItemInfo SavePageListInfo
            {
                get
                {
                    return _savepagelistInfo;
                }
            }

            /// <summary>
            /// The CreatePageList item.
            /// </summary>
            [RepositoryItem("ecaa715d-f249-4bd9-be61-d9400594bf8e")]
            public virtual Ranorex.InputTag CreatePageList
            {
                get
                {
                    return _createpagelistInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CreatePageList item info.
            /// </summary>
            [RepositoryItemInfo("ecaa715d-f249-4bd9-be61-d9400594bf8e")]
            public virtual RepoItemInfo CreatePageListInfo
            {
                get
                {
                    return _createpagelistInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
