///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PagelistCreation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PagelistActions recording.
    /// </summary>
    [TestModule("b7b24840-964a-4af7-838a-7058e624c1f7", ModuleType.Recording, 1)]
    public partial class PagelistActions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PagelistCreationRepository repository.
        /// </summary>
        public static PagelistCreationRepository repo = PagelistCreationRepository.Instance;

        static PagelistActions instance = new PagelistActions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PagelistActions()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PagelistActions Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.CreatePageList' at 28;13.", repo.ContextStudio.Container.CreatePageListInfo, new RecordItemIndex(0));
            repo.ContextStudio.Container.CreatePageList.Click("28;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.PageListName' at 549;17.", repo.ContextStudio.PageListNameInfo, new RecordItemIndex(1));
            repo.ContextStudio.PageListName.Click("549;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Pagelist Test' with focus on 'ContextStudio.PageListName'.", repo.ContextStudio.PageListNameInfo, new RecordItemIndex(2));
            repo.ContextStudio.PageListName.PressKeys("Pagelist Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.PageListPath' at 424;23.", repo.ContextStudio.PageListPathInfo, new RecordItemIndex(3));
            repo.ContextStudio.PageListPath.Click("424;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 's3://obs-vendor-dev/Reg_testing' with focus on 'ContextStudio.PageListPath'.", repo.ContextStudio.PageListPathInfo, new RecordItemIndex(4));
            repo.ContextStudio.PageListPath.PressKeys("s3://obs-vendor-dev/Reg_testing");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.SavePageList' at 66;13.", repo.ContextStudio.Container.SavePageListInfo, new RecordItemIndex(5));
            repo.ContextStudio.Container.SavePageList.Click("66;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ShowPagelist' at 24;5.", repo.ContextStudio.ShowPagelistInfo, new RecordItemIndex(6));
            repo.ContextStudio.ShowPagelist.Click("24;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Close' at 24;7.", repo.ContextStudio.CloseInfo, new RecordItemIndex(7));
            repo.ContextStudio.Close.Click("24;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DeletePageList' at 25;8.", repo.ApplicationUnderTest.DeletePageListInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.DeletePageList.Click("25;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DeletePagelistSelection' at 27;18.", repo.ApplicationUnderTest.DeletePagelistSelectionInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.DeletePagelistSelection.Click("27;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Container.UserMenu' at 55;27.", repo.ContextStudio.Container.UserMenuInfo, new RecordItemIndex(10));
            repo.ContextStudio.Container.UserMenu.Click("55;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Logout' at 66;19.", repo.ContextStudio.LogoutInfo, new RecordItemIndex(11));
            repo.ContextStudio.Logout.Click("66;19");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
